; @package    JEM
; @subpackage JEM Jubilee Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2005-2009 Christoph Lukes
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_JUBILEE_EVENTS_IN_MODULE="Arrangementer i modulen"
MOD_JEM_JUBILEE_EVENTS_IN_MODULE_DESC="Antall arrangementer vist i modulen."
MOD_JEM_JUBILEE_SHOW_NO_EVENTS="Vis 'Ingen arrangementer'"
MOD_JEM_JUBILEE_SHOW_NO_EVENTS_DESC="Vis tekst hvis ingen arrangementer ble funnet. Ellers vil ikke modulen vises."
MOD_JEM_JUBILEE_PUBLISHING_STATE="Publiseringsstatus"
MOD_JEM_JUBILEE_PUBLISHING_STATE_DESC="Velg om du vil vise arkiverte arrangementer, publiserte arrangementer, eller begge deler. Hvis du lar JEM arkivere gamle arrangementer kan du her velge mellom 'Dagens arrangementer' (publisert) og 'Jubileumsarrangementer' (arkivert)."
MOD_JEM_JUBILEE_PUBLISHED_EVENTS="Publiserte arrangementer"
MOD_JEM_JUBILEE_ARCHIVED_EVENTS="Arkiverte arrangementer"
MOD_JEM_JUBILEE_BOTH_EVENTS="Begge deler"
MOD_JEM_JUBILEE_OFFSET_DAYS="Dagforskyvning"
MOD_JEM_JUBILEE_OFFSET_DAYS_DESC="Flytter datoen inn i fremtiden (positive verdier) eller inn i fortiden (negative verdier)."
MOD_JEM_JUBILEE_DATE_MATCH_MODE="Samsvarsmodus for dato"
MOD_JEM_JUBILEE_DATE_MATCH_MODE_DESC="Vis flerdagers arrangementer hvis dagen og måneden samsvarer med deres startdato, sluttdato, en av dem, eller en hvilken som helst dato mellom start- og sluttdato. For endags arrangementer er det ingen forskjell."
MOD_JEM_JUBILEE_SHOW_PAST_YEAR_EVENTS="Inkluder tidligere år"
MOD_JEM_JUBILEE_SHOW_PAST_YEAR_EVENTS_DESC="Hvis satt til JA, vil arrangementene fra tidligere år inkluderes"
MOD_JEM_JUBILEE_DATE_MATCH_FROM_START_TO_END="Når som helst fra start- til sluttdato"
MOD_JEM_JUBILEE_DATE_MATCH_ON_START="Nøyaktig på startdato"
MOD_JEM_JUBILEE_DATE_MATCH_ON_END="Nøyaktig på sluttdato"
MOD_JEM_JUBILEE_DATE_MATCH_ON_START_OR_END="Nøyaktig på start- eller sluttdato"
MOD_JEM_JUBILEE_VENUE="Lokasjon"
MOD_JEM_JUBILEE_MAX_TITLE_LENGTH="Maks. tittellengde"
MOD_JEM_JUBILEE_MAX_TITLE_LENGTH_DESC="Maks. lengde på tittelen."
MOD_JEM_JUBILEE_LINK_TO_DETAILS="Lenke til arrangement på tittel"
MOD_JEM_JUBILEE_LINK_TO_DETAILS_DESC="Lenke til arrangementssiden på tittel."
MOD_JEM_JUBILEE_EVENT_LINK_EVENT_LAYOUT="Oppsett for arrangementsblokk"
MOD_JEM_JUBILEE_EVENT_LINK_EVENT_LAYOUT_DESC="Valgfritt tving oppsettet for arrangementsblokk når et arrangement åpnes fra denne modulen."
MOD_JEM_JUBILEE_EVENT_LINK_VENUE_LAYOUT="Oppsett for lokasjonsblokk"
MOD_JEM_JUBILEE_EVENT_LINK_VENUE_LAYOUT_DESC="Valgfritt tving oppsettet for lokasjonsblokk når et arrangement åpnes fra denne modulen."
MOD_JEM_JUBILEE_EVENT_LINK_LAYOUT_DETAILS="Detaljer"
MOD_JEM_JUBILEE_EVENT_LINK_LAYOUT_COMPACT="Kompakt"
MOD_JEM_JUBILEE_SHOWDESC="Vis beskrivelse"
MOD_JEM_JUBILEE_SHOWDESC_DESC="Vis eller skjul arrangementsbeskrivelsen."
MOD_JEM_JUBILEE_SHOWFLYER="Vis plakat"
MOD_JEM_JUBILEE_SHOWFLYER_DESC="Vis eller skjul arrangementets bilde."
MOD_JEM_JUBILEE_SHOWVENUE="Vis lokasjon"
MOD_JEM_JUBILEE_SHOWVENUE_DESC="Vis eller skjul lokasjon."
MOD_JEM_JUBILEE_SHOWCATEGORY="Vis kategori"
MOD_JEM_JUBILEE_SHOWCATEGORY_DESC="Vis eller skjul kategori."
MOD_JEM_JUBILEE_LINK_TO_CATEGORY="Lenke til kategori"
MOD_JEM_JUBILEE_LINK_TO_CATEGORY_DESC="Lenke til kategorien. Bare hvis Vis kategori er valgt ovenfor!"
MOD_JEM_JUBILEE_LINK_TO_VENUE="Lenke til lokasjon"
MOD_JEM_JUBILEE_LINK_TO_VENUE_DESC="Lenke til lokasjonen. Bare hvis Vis lokasjon er valgt ovenfor!"
MOD_JEM_JUBILEE_FLYER_LINKS_TO="Plakat lenker til..."
MOD_JEM_JUBILEE_FLYER_LINKS_TO_DESC="Et klikk på plakatbildet vil vise bildet i original størrelse på full side, i et modalt popup-vindu, eller åpner arrangementets detaljvisning. Denne innstillingen krever at Vis plakat er satt til Ja."
MOD_JEM_JUBILEE_FLYER_LINK_IMAGE_PAGE="Bilde på full side"
MOD_JEM_JUBILEE_FLYER_LINK_IMAGE_MODAL="Bilde i modalt vindu"
MOD_JEM_JUBILEE_FLYER_LINK_EVENT_DETAILS="Arrangementets detaljvisning"
MOD_JEM_JUBILEE_DATE="Dato"
MOD_JEM_JUBILEE_CATEGORY_ID="Kategorier"
MOD_JEM_JUBILEE_CATEGORY_ID_DESC="Velg kategorier for å begrense utdataene til dem. La stå tomt hvis du vil vise alle arrangementer."
MOD_JEM_JUBILEE_VENUE_ID="Lokasjoner"
MOD_JEM_JUBILEE_VENUE_ID_DESC="Velg lokasjoner for å begrense utdataene til dem. La stå tomt hvis du vil vise alle arrangementer."
MOD_JEM_JUBILEE_STATE="Fylke"
MOD_JEM_JUBILEE_STATE_DESC="Skriv inn kommaseparerte fylker for å begrense arrangementene til de valgte. La stå tomt for å vise arrangementer fra alle fylker."
MOD_JEM_JUBILEE_STATE_MODE="Samsvarsmodus for fylke"
MOD_JEM_JUBILEE_STATE_MODE_DESC="Velg om fylket må samsvare helt med én av strengene gitt ovenfor, eller bare inneholde én."
MOD_JEM_JUBILEE_STATE_MODE_EXACTMATCH="Fullstendig samsvar"
MOD_JEM_JUBILEE_STATE_MODE_CONTAINS="Inneholder"
MOD_JEM_JUBILEE_SHOW_DATE_OR_YEAR_DIFFERENCE="Visningstype for dato"
MOD_JEM_JUBILEE_SHOW_DATE_OR_YEAR_DIFFERENCE_DESC="Velg for å skjule dato eller vise den formaterte datoen eller årsforskjellen fra dagens dato til arrangementsdatoen."
MOD_JEM_JUBILEE_HIDE_DATE="Skjul dato"
MOD_JEM_JUBILEE_SHOW_DATE="Vis dato"
MOD_JEM_JUBILEE_SHOW_YEAR_DIFFERENCE="Vis årsforskjell"
MOD_JEM_JUBILEE_DATE_FORMAT="Datoformat"
MOD_JEM_JUBILEE_DATE_FORMAT_DESC="Datoformat som bruker PHP-datoformatet, for eksempel: 'j. M Y'. For mer informasjon <a href='https://www.php.net/manual/en/datetime.format.php' target='_blank'>besøk PHP-manualen</a>."
MOD_JEM_JUBILEE_SHOWTIME="Vis tid"
MOD_JEM_JUBILEE_SHOWTIME_DESC="Vis eller skjul tid."
MOD_JEM_JUBILEE_TIME_FORMAT="Tidsformat"
MOD_JEM_JUBILEE_TIME_FORMAT_DESC="Tidsformat som bruker PHP-tidsformatet, for eksempel: 'H:i'. For mer informasjon <a href='https://www.php.net/manual/en/datetime.format.php' target='_blank'>besøk PHP-manualen</a>."
MOD_JEM_JUBILEE_MODULE_CLASS_SUFFIX="Suffiks for modulklasse"
MOD_JEM_JUBILEE_MODULE_CLASS_SUFFIX_DESC="Et suffiks som skal brukes på modulens CSS-klasse, dette tillater individuell modulstyling."
MOD_JEM_JUBILEE_CACHING="Bufring"
MOD_JEM_JUBILEE_CACHING_DESC="Velg om innholdet i denne modulen skal bufres."
MOD_JEM_JUBILEE_CACHE_TIME="Bufringstid"
MOD_JEM_JUBILEE_CACHE_TIME_DESC="Tiden før modulen bufres på nytt."
MOD_JEM_JUBILEE_ALLOW_LINEBREAK="Tillat linjeskift"
MOD_JEM_JUBILEE_ALLOW_LINEBREAK_DESC="Tillat linjeskift eller erstatt dem med et mellomrom."
MOD_JEM_JUBILEE_MAX_DESCRIPTION_LENGTH="Maks. beskrivelseslengde"
MOD_JEM_JUBILEE_MAX_DESCRIPTION_LENGTH_DESC="Begrens beskrivelsen som vises til dette antallet tegn."
MOD_JEM_JUBILEE_FIELD_READMORE_DESC="Hvis satt til 'Ja', vil 'Les mer …'-lenken vises hvis arrangementsbeskrivelsen har et 'Les mer'-brudd."
MOD_JEM_JUBILEE_FIELD_READMORE_LABEL="Vis 'Les mer …'-brudd"
MOD_JEM_JUBILEE_SHOW_MORE_INFORMATION="Vis mer informasjon"
MOD_JEM_JUBILEE_SHOW_MORE_INFORMATION_DESC="Vis en 'Mer informasjon'-lenke eller -knapp når arrangementet har en tilknyttet artikkel."
MOD_JEM_JUBILEE_SHOW_MORE_INFORMATION_TITLE="Vis tittel for mer informasjon"
MOD_JEM_JUBILEE_SHOW_MORE_INFORMATION_TITLE_DESC="Vis den tilknyttede artikkeltittelen etter 'Mer informasjon'-lenketeksten."
MOD_JEM_JUBILEE_READMORE_LINK="Ja (lenke)"
MOD_JEM_JUBILEE_READMORE_BUTTON="Ja (knapp)"
MOD_JEM_JUBILEE_MORE_INFORMATION_LINK="Ja (lenke)"
MOD_JEM_JUBILEE_MORE_INFORMATION_BUTTON="Ja (knapp)"
MOD_JEM_JUBILEE_SHOWCALENDAR="Vis kalender"
MOD_JEM_JUBILEE_SHOWCALENDAR_DESC="Viser et kalenderbilde med dagen og måneden modulen søker arrangementer for."
MOD_JEM_JUBILEE_COLOR="Farge"
MOD_JEM_JUBILEE_COLOR_DESC="Farge på kalenderbildet. Hvis 'brukerdefinert' er valgt, vil fargeverdien hentes fra feltet nedenfor."
MOD_JEM_JUBILEE_BLUE="Blå"
MOD_JEM_JUBILEE_GREEN="Grønn"
MOD_JEM_JUBILEE_ORANGE="Oransje"
MOD_JEM_JUBILEE_RED="Rød"
MOD_JEM_JUBILEE_USER="brukerdefinert"
MOD_JEM_JUBILEE_USER_COLOR="Brukerfarge"
MOD_JEM_JUBILEE_USER_COLOR_DESC="Farge brukt hvis 'brukerdefinert' er valgt ovenfor."
MOD_JEM_JUBILEE_SHUFFLE="Bland arrangementer"
MOD_JEM_JUBILEE_SHUFFLE_DESC="Hvis det er flere arrangementer å vise, velg arrangementer tilfeldig fra poolen."
MOD_JEM_JUBILEE_SHUFFLE_COUNT="Grense for blande-pool"
MOD_JEM_JUBILEE_SHUFFLE_COUNT_DESC="Begrenser arrangementer lest fra databasen til maks. antall, men vil korrigeres til minst antall arrangementer som skal vises."
MOD_JEM_JUBILEE_INTROTEXT="Innledningstekst"
MOD_JEM_JUBILEE_INTROTEXT_DESC="Tekst vist over arrangementene rett ved siden av kalenderbildet. Støttede bbCodes er [day], [month], [year]. La stå tomt for å vise ingen innledningstekst."
MOD_JEM_JUBILEE_ORDER="Rekkefølge på arrangementer"
MOD_JEM_JUBILEE_ORDER_DESC="Rekkefølgen arrangementene vil vises i."
MOD_JEM_JUBILEE_ORDER_ASCENDING="Dato stigende"
MOD_JEM_JUBILEE_ORDER_DESCENDING="Dato synkende"
MOD_JEM_JUBILEE="JEM - Jubileumsmodul"
MOD_JEM_JUBILEE_XML_DESCRIPTION="JEM Jubileumsmodul for jubileumsarrangementer."
MOD_JEM_JUBILEE_EVENT_TREE_MODE="Event hierarki"
MOD_JEM_JUBILEE_EVENT_TREE_MODE_DESC="Velg om denne modulen viser toppnivåhendelser, programelementer eller begge deler."
MOD_JEM_JUBILEE_EVENT_TREE_MODE_CALENDAR="Kalender standard"
MOD_JEM_JUBILEE_EVENT_TREE_MODE_PARENTS="Overordnede hendelser bare"
MOD_JEM_JUBILEE_EVENT_TREE_MODE_CHILDREN="Kun Subevents"
MOD_JEM_JUBILEE_EVENT_TREE_MODE_ALL="Overordnede hendelser og overhengere"

; Frontend
MOD_JEM_JUBILEE_TODAY="I dag"
MOD_JEM_JUBILEE_TOMORROW="I morgen"
MOD_JEM_JUBILEE_YESTERDAY="I går"
MOD_JEM_JUBILEE_FROM="Fra %s"
MOD_JEM_JUBILEE_UNTIL="Til %s"
MOD_JEM_JUBILEE_FROM_UNTIL="Fra %s til %s"
MOD_JEM_JUBILEE_ON_DATE="På %s"
MOD_JEM_JUBILEE_READMORE="Les mer..."
MOD_JEM_JUBILEE_MORE_INFORMATION="Mer informasjon"
MOD_JEM_JUBILEE_READMORE_REGISTER="Logg inn for å lese flere detaljer."
; MOD_JEM_JUBILEE_NO_DESCRIPTION=""
MOD_JEM_JUBILEE_NO_EVENTS="Ingen arrangementer funnet."
MOD_JEM_JUBILEE_YEAR_AGO="%s år siden"
MOD_JEM_JUBILEE_YEARS_AGO="%s år siden"
MOD_JEM_JUBILEE_NEARLY_YEAR_AGO="Nesten %s år siden"
MOD_JEM_JUBILEE_NEARLY_YEARS_AGO="Nesten %s år siden"
MOD_JEM_JUBILEE_OVER_YEAR_AGO="Mer enn %s år siden"
MOD_JEM_JUBILEE_OVER_YEARS_AGO="Mer enn %s år siden"
MOD_JEM_JUBILEE_MONTHS_AGO="%s måneder siden"
MOD_JEM_JUBILEE_DAYS_AGO="%s dager siden"
MOD_JEM_JUBILEE_YEAR_AHEAD="%s år fremover"
MOD_JEM_JUBILEE_YEARS_AHEAD="%s år fremover"
MOD_JEM_JUBILEE_NEARLY_YEAR_AHEAD="Nesten %s år fremover"
MOD_JEM_JUBILEE_NEARLY_YEARS_AHEAD="Nesten %s år fremover"
MOD_JEM_JUBILEE_OVER_YEAR_AHEAD="Mer enn %s år fremover"
MOD_JEM_JUBILEE_OVER_YEARS_AHEAD="Mer enn %s år fremover"
MOD_JEM_JUBILEE_MONTHS_AHEAD="%s måneder fremover"
MOD_JEM_JUBILEE_DAYS_AHEAD="%s dager fremover"
MOD_JEM_JUBILEE_DAYS_LEFT="%s dager igjen"
MOD_JEM_JUBILEE_ENDED_YEAR_AGO="Avsluttet %s år siden"
MOD_JEM_JUBILEE_ENDED_YEARS_AGO="Avsluttet %s år siden"
MOD_JEM_JUBILEE_ENDED_NEARLY_YEAR_AGO="Avsluttet nesten %s år siden"
MOD_JEM_JUBILEE_ENDED_NEARLY_YEARS_AGO="Avsluttet nesten %s år siden"
MOD_JEM_JUBILEE_ENDED_OVER_YEAR_AGO="Avsluttet mer enn %s år siden"
MOD_JEM_JUBILEE_ENDED_OVER_YEARS_AGO="Avsluttet mer enn %s år siden"
MOD_JEM_JUBILEE_ENDED_DAY_AGO="Avsluttet %s dag siden"
MOD_JEM_JUBILEE_ENDED_DAYS_AGO="Avsluttet %s dager siden"
MOD_JEM_JUBILEE_STARTED_YEAR_AGO="Startet %s år siden"
MOD_JEM_JUBILEE_STARTED_YEARS_AGO="Startet %s år siden"
MOD_JEM_JUBILEE_STARTED_NEARLY_YEAR_AGO="Startet nesten %s år siden"
MOD_JEM_JUBILEE_STARTED_NEARLY_YEARS_AGO="Startet nesten %s år siden"
MOD_JEM_JUBILEE_STARTED_OVER_YEAR_AGO="Startet mer enn %s år siden"
MOD_JEM_JUBILEE_STARTED_OVER_YEARS_AGO="Startet mer enn %s år siden"
MOD_JEM_JUBILEE_STARTED_DAYS_AGO="Startet %s dager siden"
; Module intro and footer text
MOD_JEM_JUBILEE_MODULE_TEXT_BLOCK="Modulens innledningstekst og bunntekst"
MOD_JEM_JUBILEE_SHOW_INTROTEXT="Vis innledningstekst"
MOD_JEM_JUBILEE_SHOW_INTROTEXT_DESC="Vis egendefinert tekst over modulens innhold."
MOD_JEM_JUBILEE_SHOW_FOOTERTEXT="Vis bunntekst"
MOD_JEM_JUBILEE_SHOW_FOOTERTEXT_DESC="Vis egendefinert tekst under modulens innhold."
MOD_JEM_JUBILEE_FOOTERTEXT="Bunntekst"
MOD_JEM_JUBILEE_FOOTERTEXT_DESC="Tekst som vises under modulens innhold."

