; @package    JEM
; @subpackage JEM Teaser Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2005-2009 Christoph Lukes
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_TEASER_EVENTS_IN_MODULE="Arrangementer i modulen"
MOD_JEM_TEASER_EVENTS_IN_MODULE_DESC="Antall arrangementer vist i modulen."
MOD_JEM_TEASER_UPCOMING_ARCHIVED_OR_CURRENT="Visningstype for arrangementer"
MOD_JEM_TEASER_UPCOMING_ARCHIVED_OR_CURRENT_DESC="Velg om du vil vise kommende, ikke-fullførte, arkiverte eller dagens arrangementer."
MOD_JEM_TEASER_UPCOMING_EVENTS="Kommende"
MOD_JEM_TEASER_UNFINISHED_EVENTS="Ikke-fullførte"
MOD_JEM_TEASER_ARCHIVED_EVENTS="Arkiverte"
MOD_JEM_TEASER_CURRENT_EVENTS="I dag"
MOD_JEM_TEASER_FEATURED_EVENTS="Utvalgte"
MOD_JEM_TEASER_SHOW_NO_EVENTS="Vis 'Ingen arrangementer'"
MOD_JEM_TEASER_SHOW_NO_EVENTS_DESC="Vis tekst hvis ingen arrangementer ble funnet. Ellers vil ikke modulen vises."
MOD_JEM_TEASER_OFFSET_HOURS="Tidsforskyvning (i timer)"
MOD_JEM_TEASER_OFFSET_HOURS_DESC="Flytter tid inn i fremtiden (positive verdier) eller inn i fortiden (negative verdier). Brukes kun til å vise ikke-arkiverte arrangementer; på dagens arrangementer rundes det av til hele dager. <br>Eksempler: For å vise arrangementer som avsluttet minst to timer siden, sett type til Ikke-fullførte arrangementer og forskyvning til -2. For å vise arrangementer som starter om én uke eller senere, sett type til Kommende arrangementer og forskyvning til 168 (7 * 24). For å vise morgendagens arrangementer, sett type til I dag og forskyvning til 24."
MOD_JEM_TEASER_VENUE="Sted"
MOD_JEM_TEASER_MAX_TITLE_LENGTH="Maks. tittellengde"
MOD_JEM_TEASER_MAX_TITLE_LENGTH_DESC="Maks. lengde på tittelen."
MOD_JEM_TEASER_LINK_TO_DETAILS="Lenke til arrangement på tittel"
MOD_JEM_TEASER_LINK_TO_DETAILS_DESC="Lenke til arrangementssiden på tittel."
MOD_JEM_TEASER_EVENT_LINK_EVENT_LAYOUT="Oppsett for arrangementsblokk"
MOD_JEM_TEASER_EVENT_LINK_EVENT_LAYOUT_DESC="Valgfritt tving oppsettet for arrangementsblokk når et arrangement åpnes fra denne modulen."
MOD_JEM_TEASER_EVENT_LINK_VENUE_LAYOUT="Oppsett for lokasjonsblokk"
MOD_JEM_TEASER_EVENT_LINK_VENUE_LAYOUT_DESC="Valgfritt tving oppsettet for lokasjonsblokk når et arrangement åpnes fra denne modulen."
MOD_JEM_TEASER_EVENT_LINK_LAYOUT_DETAILS="Detaljer"
MOD_JEM_TEASER_EVENT_LINK_LAYOUT_COMPACT="Kompakt"
MOD_JEM_TEASER_LINK_TO_CATEGORY="Lenke til kategori"
MOD_JEM_TEASER_LINK_TO_CATEGORY_DESC="Lenke til kategorien."
MOD_JEM_TEASER_SHOW_CATEGORY="Vis kategori"
MOD_JEM_TEASER_SHOW_CATEGORY_DESC="Vis eller skjul arrangementskategorien."
MOD_JEM_TEASER_SHOW_VENUE="Vis arrangement"
MOD_JEM_TEASER_SHOW_VENUE_DESC="Vis eller skjul arrangementslokasjonen."
MOD_JEM_TEASER_LINK_TO_VENUE="Lenke til lokasjon"
MOD_JEM_TEASER_LINK_TO_VENUE_DESC="Lenke til lokasjonen."
MOD_JEM_TEASER_SHOW_DESCRIPTION_EVENT="Vis beskrivelse"
MOD_JEM_TEASER_SHOW_DESCRIPTION_EVENT_DESC="Vis beskrivelse av arrangementet."
MOD_JEM_TEASER_SHOW_IMAGE_EVENT="Vis arrangementsbilde"
MOD_JEM_TEASER_SHOW_IMAGE_EVENT_DESC="Vis bilde av arrangementet."
MOD_JEM_TEASER_SHOW_IMAGE_VENUE="Vis lokasjonsbilde"
MOD_JEM_TEASER_SHOW_IMAGE_VENUE_DESC="Vis bilde av lokasjonen."
MOD_JEM_TEASER_USE_MODAL="Modalt vindu"
MOD_JEM_TEASER_USE_MODAL_DESC="Det modale vinduet viser bildet i original størrelse etter et klikk med en fin effekt innenfor gjeldende skjerm"
MOD_JEM_TEASER_DATE="Dato"
MOD_JEM_TEASER_CATEGORY_ID="Kategorier"
MOD_JEM_TEASER_CATEGORY_ID_DESC="Velg kategorier for å begrense utdataene til dem. La stå tomt hvis du vil vise alle arrangementer."
MOD_JEM_TEASER_VENUE_ID="Lokasjoner"
MOD_JEM_TEASER_VENUE_ID_DESC="Velg lokasjoner for å begrense utdataene til dem. La stå tomt hvis du vil vise alle arrangementer."
MOD_JEM_TEASER_EVENT_ID="Arrangements-ID"
MOD_JEM_TEASER_EVENT_ID_DESC="Skriv inn kommaseparerte arrangements-ID-er for å begrense utdataene til dem. La stå tomt hvis du vil vise alle arrangementer."
MOD_JEM_TEASER_STATE="Fylke"
MOD_JEM_TEASER_STATE_DESC="Skriv inn kommaseparerte fylker for å begrense arrangementene til de valgte. La stå tomt for å vise arrangementer fra alle fylker."
MOD_JEM_TEASER_STATE_MODE="Samsvarsmodus for fylke"
MOD_JEM_TEASER_STATE_MODE_DESC="Velg om fylket må samsvare helt med én av strengene gitt ovenfor, eller bare inneholde én."
MOD_JEM_TEASER_STATE_MODE_EXACTMATCH="Fullstendig samsvar"
MOD_JEM_TEASER_STATE_MODE_CONTAINS="Inneholder"
MOD_JEM_TEASER_COUNTRIES="Land"
MOD_JEM_TEASER_COUNTRIES_DESC="Velg land for å begrense utdataene til dem. La stå tomt hvis du vil vise alle arrangementer."
MOD_JEM_TEASER_SHOW_DATE="Vis dato"
MOD_JEM_TEASER_SHOW_DAY_DIFFERENCE="Vis dagsforskjell"
MOD_JEM_TEASER_SHOW_DATE_OR_DAY_DIFFERENCE="Visningstype for dato"
MOD_JEM_TEASER_SHOW_DATE_OR_DAY_DIFFERENCE_DESC="Velg å vise den formaterte datoen eller dagsforskjellen fra dagens dato til arrangementsdatoen. Merk: Tiden vil bli skjult når dagsforskjell er valgt."
MOD_JEM_TEASER_DATE_FORMAT="Datoformat"
MOD_JEM_TEASER_DATE_FORMAT_DESC="Datoformat som bruker PHP-datoformatet, for eksempel: 'j. M Y'. For mer informasjon <a href='https://www.php.net/manual/en/datetime.format.php' target='_blank'>besøk PHP-manualen</a>."
MOD_JEM_TEASER_TIME_FORMAT="Tidsformat"
MOD_JEM_TEASER_TIME_FORMAT_DESC="Tidsformat som bruker PHP-tidsformatet, for eksempel: 'H:i'. For mer informasjon <a href='https://www.php.net/manual/en/datetime.format.php' target='_blank'>besøk PHP-manualen</a>."
MOD_JEM_TEASER_MODULE_CLASS_SUFFIX="Suffiks for modulklasse"
MOD_JEM_TEASER_MODULE_CLASS_SUFFIX_DESC="Et suffiks som skal brukes på modulens CSS-klasse, dette tillater individuell modulstyling."
MOD_JEM_TEASER_CACHING="Bufring"
MOD_JEM_TEASER_CACHING_DESC="Velg om innholdet i denne modulen skal bufres."
MOD_JEM_TEASER_CACHE_TIME="Bufringstid"
MOD_JEM_TEASER_CACHE_TIME_DESC="Tiden før modulen bufres på nytt."
MOD_JEM_TEASER_ALLOW_LINEBREAK="Tillat linjeskift"
MOD_JEM_TEASER_ALLOW_LINEBREAK_DESC="Tillat linjeskift eller erstatt dem med et mellomrom."
MOD_JEM_TEASER_COLOR="Farge"
MOD_JEM_TEASER_COLOR_DESC="Farge på kalenderbildet. 'fra Kategori': kategorifargen vil bli brukt hvis unik, ellers reservefargen. 'fra Lokasjon': lokasjonsfargen vil bli brukt hvis tilgjengelig, ellers reservefargen."
MOD_JEM_TEASER_MAX_DESCRIPTION_LENGTH="Maks. beskrivelseslengde"
MOD_JEM_TEASER_MAX_DESCRIPTION_LENGTH_DESC="Begrens beskrivelsen som vises til dette antallet tegn."
MOD_JEM_TEASER_BLUE="Blå"
MOD_JEM_TEASER_GREEN="Grønn"
MOD_JEM_TEASER_ORANGE="Oransje"
MOD_JEM_TEASER_RED="Rød"
MOD_JEM_TEASER_CATEGORY_COLOR="fra Kategori"
MOD_JEM_TEASER_VENUE_COLOR="fra Lokasjon"
MOD_JEM_TEASER_FALLBACK_COLOR="Reservefarge"
MOD_JEM_TEASER_FALLBACK_COLOR_DESC="Farge i HEX-kode brukt for 'Reservefarge' eller hvis 'fra Kategori' er valgt og ingen kategorifargeverdi kan finnes."
MOD_JEM_TEASER_FIELD_READMORE_DESC="Hvis satt til 'Ja', vil 'Les mer …'-lenken vises hvis arrangementsbeskrivelsen har et 'Les mer'-brudd."
MOD_JEM_TEASER_FIELD_READMORE_LABEL="Vis 'Les mer …'-brudd"
MOD_JEM_TEASER_SHOW_MORE_INFORMATION="Vis mer informasjon"
MOD_JEM_TEASER_SHOW_MORE_INFORMATION_DESC="Vis en 'Mer informasjon'-lenke eller -knapp når arrangementet har en tilknyttet artikkel."
MOD_JEM_TEASER_SHOW_MORE_INFORMATION_TITLE="Vis tittel for mer informasjon"
MOD_JEM_TEASER_SHOW_MORE_INFORMATION_TITLE_DESC="Vis den tilknyttede artikkeltittelen etter 'Mer informasjon'-lenketeksten."
MOD_JEM_TEASER_READMORE_LINK="Ja (lenke)"
MOD_JEM_TEASER_READMORE_BUTTON="Ja (knapp)"
MOD_JEM_TEASER_MORE_INFORMATION_LINK="Ja (lenke)"
MOD_JEM_TEASER_MORE_INFORMATION_BUTTON="Ja (knapp)"

MOD_JEM_TEASER="JEM - Teasermodul"
MOD_JEM_TEASER_XML_DESCRIPTION="JEM Teasermodul for siste arrangementer."

; Frontend
MOD_JEM_TEASER_TODAY="I dag"
MOD_JEM_TEASER_TOMORROW="I morgen"
MOD_JEM_TEASER_YESTERDAY="I går"
MOD_JEM_TEASER_DAYS_AGO="%s dager siden"
MOD_JEM_TEASER_DAYS_AHEAD="%s dager fremover"
MOD_JEM_TEASER_ENDED_DAYS_AGO="Avsluttet %s dager siden"
MOD_JEM_TEASER_STARTED_DAYS_AGO="Startet %s dager siden"
MOD_JEM_TEASER_FROM="Fra %s"
MOD_JEM_TEASER_UNTIL="Til %s"
MOD_JEM_TEASER_FROM_UNTIL="Fra %s til %s"
MOD_JEM_TEASER_ON_DATE="På %s"
MOD_JEM_TEASER_READMORE="Les mer..."
MOD_JEM_TEASER_MORE_INFORMATION="Mer informasjon"
MOD_JEM_TEASER_READMORE_REGISTER="Logg inn for å lese flere detaljer."
MOD_JEM_TEASER_NO_DESCRIPTION=""
MOD_JEM_TEASER_NO_EVENTS="Ingen arrangementer funnet."
MOD_JEM_TEASER_ALL_DAY="Hele dagen"
MOD_JEM_TEASER_VENUE_COLOR_LABEL="Bruk lokasjonsfarge"
MOD_JEM_TEASER_VENUE_COLOR_DESC="Bruk lokasjonsfarge i lokasjonsetiketten"
MOD_JEM_TEASER_CATEGORY_COLOR_LABEL="Bruk kategorifarge"
MOD_JEM_TEASER_CATEGORY_COLOR_DESC="Bruk kategorifarge i kategorietiketten"
MOD_JEM_TEASER_COLOR_NO="Nei"
MOD_JEM_TEASER_COLOR_TEXT="Fargetekst"
MOD_JEM_TEASER_COLOR_BG="Fargebakgrunn"
; Module intro and footer text
MOD_JEM_TEASER_MODULE_TEXT_BLOCK="Module intro and footer"
MOD_JEM_TEASER_SHOW_INTROTEXT="Show intro text"
MOD_JEM_TEASER_SHOW_INTROTEXT_DESC="Display custom text above the module content."
MOD_JEM_TEASER_INTROTEXT="Intro text"
MOD_JEM_TEASER_INTROTEXT_DESC="Text displayed above the module content."
MOD_JEM_TEASER_SHOW_FOOTERTEXT="Show footer text"
MOD_JEM_TEASER_SHOW_FOOTERTEXT_DESC="Display custom text below the module content."
MOD_JEM_TEASER_FOOTERTEXT="Footer text"
MOD_JEM_TEASER_FOOTERTEXT_DESC="Text displayed below the module content."

