; @package    JEM
; @subpackage JEM Map Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_MAP="JEM - Lokasjonskartmodul"
MOD_JEM_MAP_XML_DESCRIPTION="Displays JEM venues on an interactive map that have latitude and longitude set in JEM."
MOD_JEM_MAP_SHOW_COUNTRY_FILTER="Vis landfilter"
MOD_JEM_MAP_SHOW_COUNTRY_FILTER_DESC="Vis en landvelger over kartet."
MOD_JEM_MAP_COUNTRY_FILTER="Landfilter"
MOD_JEM_MAP_ALL_COUNTRIES="Alle land"
MOD_JEM_MAP_DEFAULT_COUNTRY="Standard landfilter"
MOD_JEM_MAP_DEFAULT_COUNTRY_DESC="Velg landet som brukes som standard lokasjonsfilter for kartet. La stå tomt for å vise lokasjoner fra alle land."
; Module intro and footer text
MOD_JEM_MAP_MODULE_TEXT_BLOCK="Modulens innledningstekst og bunntekst"
MOD_JEM_MAP_SHOW_INTROTEXT="Vis innledningstekst"
MOD_JEM_MAP_SHOW_INTROTEXT_DESC="Vis egendefinert tekst over modulens innhold."
MOD_JEM_MAP_INTROTEXT="Innledningstekst"
MOD_JEM_MAP_INTROTEXT_DESC="Tekst som vises over modulens innhold."
MOD_JEM_MAP_SHOW_FOOTERTEXT="Vis bunntekst"
MOD_JEM_MAP_SHOW_FOOTERTEXT_DESC="Vis egendefinert tekst under modulens innhold."
MOD_JEM_MAP_FOOTERTEXT="Bunntekst"
MOD_JEM_MAP_FOOTERTEXT_DESC="Tekst som vises under modulens innhold."

