; @package    JEM
; @subpackage JEM Latest Events Wide Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2005-2009 Christoph Lukes
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_WIDE="JEM - Bredmodul"
MOD_JEM_WIDE_XML_DESCRIPTION="Denne modulen viser arrangementer i et bredt oppsett."
MOD_JEM_WIDE_EVENT_LINK_EVENT_LAYOUT="Oppsett for arrangementsblokk"
MOD_JEM_WIDE_EVENT_LINK_EVENT_LAYOUT_DESC="Valgfritt tving oppsettet for arrangementsblokk når et arrangement åpnes fra denne modulen."
MOD_JEM_WIDE_EVENT_LINK_VENUE_LAYOUT="Oppsett for lokasjonsblokk"
MOD_JEM_WIDE_EVENT_LINK_VENUE_LAYOUT_DESC="Valgfritt tving oppsettet for lokasjonsblokk når et arrangement åpnes fra denne modulen."
MOD_JEM_WIDE_EVENT_LINK_LAYOUT_DETAILS="Detaljer"
MOD_JEM_WIDE_EVENT_LINK_LAYOUT_COMPACT="Kompakt"
; Module intro and footer text
MOD_JEM_WIDE_MODULE_TEXT_BLOCK="Modulens innledningstekst og bunntekst"
MOD_JEM_WIDE_SHOW_INTROTEXT="Vis innledningstekst"
MOD_JEM_WIDE_SHOW_INTROTEXT_DESC="Vis egendefinert tekst over modulens innhold."
MOD_JEM_WIDE_INTROTEXT="Innledningstekst"
MOD_JEM_WIDE_INTROTEXT_DESC="Tekst som vises over modulens innhold."
MOD_JEM_WIDE_SHOW_FOOTERTEXT="Vis bunntekst"
MOD_JEM_WIDE_SHOW_FOOTERTEXT_DESC="Vis egendefinert tekst under modulens innhold."
MOD_JEM_WIDE_FOOTERTEXT="Bunntekst"
MOD_JEM_WIDE_FOOTERTEXT_DESC="Tekst som vises under modulens innhold."

