; @package    JEM
; @subpackage JEM Tag Plugin for AcyMailing 5.x
; @copyright  (C) 2013-2017 joomlaeventmanager.net
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note : All ini files need to be saved as UTF-8 - No BOM

PLG_TAGJEM_HELP="Помощь"
PLG_TAGJEM_HELP_DESC="Нажмите кнопку помощи, чтобы получить справку."
PLG_TAGJEM_HIDE_PAST_EVENTS="Скрыть прошедшие мероприятия"
PLG_TAGJEM_HIDE_PAST_EVENTS_DESC="Вы хотите скрыть прошедшие мероприятия?"
PLG_TAGJEM_FEATURED_EVENTS="Ограничить избранными мероприятиями"
PLG_TAGJEM_FEATURED_EVENTS_DESC="Вы хотите показывать только избранные мероприятия? -- Значение по умолчанию"
PLG_TAGJEM_SHOW_IMAGES="Показывать изображения"
PLG_TAGJEM_SHOW_IMAGES_DESC="Показывать изображения мероприятий? -- Значение по умолчанию"
PLG_TAGJEM_IMAGE_WIDTH="Макс. ширина изображения"
PLG_TAGJEM_IMAGE_WIDTH_DESC="Максимальная ширина изображений мероприятий в случае выбора 'Изменять размер' выше -- Значение по умолчанию"
PLG_TAGJEM_IMAGE_HEIGHT="Макс. высота изображения"
PLG_TAGJEM_IMAGE_HEIGHT_DESC="Максимальная высота изображений мероприятий в случае выбора 'Изменять размер' выше -- Значение по умолчанию"
PLG_TAGJEM_DEFAULT_ITEM_ID="ID пункта меню по умолчанию"
PLG_TAGJEM_DEFAULT_ITEM_ID_DESC="ID пункта меню, ссылающегося на представление JEM (список)"
PLG_TAGJEM_OPTION_NO_SHOW_ALL="Нет, показывать все"
PLG_TAGJEM_OPTION_YES_FETURED_ONLY="Да, только избранные"
PLG_TAGJEM_OPTION_RESIZED="Изменять размер"
PLG_TAGJEM_TITLE="Название"
PLG_TAGJEM_DESCRIPTION="Описание"
PLG_TAGJEM_DATE="Дата"
PLG_TAGJEM_ID="ID"
PLG_TAGJEM_RESIZE="Изменять размер"
PLG_TAGJEM_TEMPLATE="Шаблон"
PLG_TAGJEM_CONTACT="Контакт"
PLG_TAGJEM_PHONE="Телефон"
PLG_TAGJEM_CELLPHONE="Мобильный / SMS"
PLG_TAGJEM_VENUE="Место проведения"
