; @package    JEM
; @subpackage JEM Upcoming Events Basic Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2005-2009 Christoph Lukes
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM="JEM - Module de base"
MOD_JEM_XML_DESCRIPTION="Ce module affiche une liste succincte d'un nombre spécifié d'événements."
MOD_JEM_EVENT_LINK_EVENT_LAYOUT="Disposition du bloc événement"
MOD_JEM_EVENT_LINK_EVENT_LAYOUT_DESC="Force facultativement la disposition du bloc événement lors de l'ouverture d'un événement depuis ce module."
MOD_JEM_EVENT_LINK_VENUE_LAYOUT="Disposition du bloc lieu"
MOD_JEM_EVENT_LINK_VENUE_LAYOUT_DESC="Force facultativement la disposition du bloc lieu lors de l'ouverture d'un événement depuis ce module."
MOD_JEM_EVENT_LINK_LAYOUT_DETAILS="Détails"
MOD_JEM_EVENT_LINK_LAYOUT_COMPACT="Compact"
; Module intro and footer text
MOD_JEM_MODULE_TEXT_BLOCK="Introduction et pied de page du module"
MOD_JEM_SHOW_INTROTEXT="Afficher le texte d'introduction"
MOD_JEM_SHOW_INTROTEXT_DESC="Affiche un texte personnalisé au-dessus du contenu du module."
MOD_JEM_INTROTEXT="Texte d'introduction"
MOD_JEM_INTROTEXT_DESC="Texte affiché au-dessus du contenu du module."
MOD_JEM_SHOW_FOOTERTEXT="Afficher le texte de pied de page"
MOD_JEM_SHOW_FOOTERTEXT_DESC="Affiche un texte personnalisé en dessous du contenu du module."
MOD_JEM_FOOTERTEXT="Texte de pied de page"
MOD_JEM_FOOTERTEXT_DESC="Texte affiché en dessous du contenu du module."

