; @package    JEM
; @subpackage JEM Map Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_MAP="JEM - Module Carte des Lieux"
MOD_JEM_MAP_XML_DESCRIPTION="Displays JEM venues on an interactive map that have latitude and longitude set in JEM."
MOD_JEM_MAP_SHOW_COUNTRY_FILTER="Afficher le filtre de pays"
MOD_JEM_MAP_SHOW_COUNTRY_FILTER_DESC="Affiche un sélecteur de pays au-dessus de la carte."
MOD_JEM_MAP_COUNTRY_FILTER="Filtre de pays"
MOD_JEM_MAP_ALL_COUNTRIES="Tous les pays"
MOD_JEM_MAP_DEFAULT_COUNTRY="Filtre de pays par défaut"
MOD_JEM_MAP_DEFAULT_COUNTRY_DESC="Sélectionnez le pays utilisé comme filtre de lieu par défaut pour la carte. Laissez vide pour afficher les lieux de tous les pays."
; Module intro and footer text
MOD_JEM_MAP_MODULE_TEXT_BLOCK="Introduction et pied de page du module"
MOD_JEM_MAP_SHOW_INTROTEXT="Afficher le texte d'introduction"
MOD_JEM_MAP_SHOW_INTROTEXT_DESC="Affiche un texte personnalisé au-dessus du contenu du module."
MOD_JEM_MAP_INTROTEXT="Texte d'introduction"
MOD_JEM_MAP_INTROTEXT_DESC="Texte affiché au-dessus du contenu du module."
MOD_JEM_MAP_SHOW_FOOTERTEXT="Afficher le texte de pied de page"
MOD_JEM_MAP_SHOW_FOOTERTEXT_DESC="Affiche un texte personnalisé en dessous du contenu du module."
MOD_JEM_MAP_FOOTERTEXT="Texte de pied de page"
MOD_JEM_MAP_FOOTERTEXT_DESC="Texte affiché en dessous du contenu du module."

