; @package    JEM
; @subpackage JEM Calendar Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2008 Toni Smillie www.qivva.com
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_CAL="JEM - Module calendrier"
MOD_JEM_CAL_XML_DESCRIPTION="Affiche les événements sur un calendrier mensuel dans une position de module."
MOD_JEM_CAL_EVENT_TREE_MODE="Hiérarchie des événements"
MOD_JEM_CAL_EVENT_TREE_MODE_DESC="Choisissez si ce module affiche les événements de niveau supérieur, les éléments du programme ou les deux."
MOD_JEM_CAL_EVENT_TREE_MODE_CALENDAR="Calendrier par défaut"
MOD_JEM_CAL_EVENT_TREE_MODE_PARENTS="Événements parents uniquement"
MOD_JEM_CAL_EVENT_TREE_MODE_CHILDREN="Subevents seulement"
MOD_JEM_CAL_EVENT_TREE_MODE_ALL="Évènements et sous-vènements parents"
MOD_JEM_CAL_SHOW_TOOLTIPS="Afficher infobulles"
MOD_JEM_CAL_SHOW_TOOLTIPS_DESC="Afficher les infobulles au survol de la souris sur les dates du calendrier."
MOD_JEM_CAL_SHOW_TOOLTIPS_TITLE="Afficher titre infobulles"
MOD_JEM_CAL_SHOW_TOOLTIPS_TITLE_DESC="Afficher le titre des infobulles."
MOD_JEM_CAL_TOOLTIPS_TITLE_SINGULAR="Titre infobulles (unique)"
MOD_JEM_CAL_TOOLTIPS_TITLE_SINGULAR_DESC="Définir le titre des infobulles à afficher si l'infobulle contient un seul événement."
MOD_JEM_CAL_TOOLTIPS_TITLE_PLURAL="Titre infobulles (plusieurs)"
MOD_JEM_CAL_TOOLTIPS_TITLE_PLURAL_DESC="Définir le titre des infobulles à afficher si l'infobulle contient plusieurs événements."
MOD_JEM_CAL_TOOLTIPS_MAX_EVENTS="Événements max. dans infobulle"
MOD_JEM_CAL_TOOLTIPS_MAX_EVENTS_DESC="Limiter le nombre d'événements à afficher dans l'infobulle, laisser vide pour aucune limite."
MOD_JEM_CAL_TOOLTIPS_MAX_EVENT_TITLE_LENGTH="Longueur max. titre événement"
MOD_JEM_CAL_TOOLTIPS_MAX_EVENT_TITLE_LENGTH_DESC="Limiter la longueur des titres des événements à afficher dans les infobulles, laisser vide pour aucune limite."
MOD_JEM_CAL_SHOW_TOOLTIPS_LINK="Afficher le lien dans l'infobulle"
MOD_JEM_CAL_SHOW_TOOLTIPS_LINK_DESC="Afficher le(s) lien(s) de l'événement dans les infobulles."
MOD_JEM_CAL_EVENT_LINK_EVENT_LAYOUT="Disposition du bloc événement"
MOD_JEM_CAL_EVENT_LINK_EVENT_LAYOUT_DESC="Force facultativement la disposition du bloc événement lors de l'ouverture d'un événement depuis ce module."
MOD_JEM_CAL_EVENT_LINK_VENUE_LAYOUT="Disposition du bloc lieu"
MOD_JEM_CAL_EVENT_LINK_VENUE_LAYOUT_DESC="Force facultativement la disposition du bloc lieu lors de l'ouverture d'un événement depuis ce module."
MOD_JEM_CAL_EVENT_LINK_LAYOUT_DETAILS="Détails"
MOD_JEM_CAL_EVENT_LINK_LAYOUT_COMPACT="Compact"
MOD_JEM_CAL_SHOW_TOOLTIPS_TIME="Afficher l'heure dans l'infobulle"
MOD_JEM_CAL_SHOW_TOOLTIPS_TIME_DESC="Afficher l'heure/les heures de l'événement dans les infobulles."
MOD_JEM_CAL_SHOW_TOOLTIPS_CATEGORY="Afficher catégorie dans infobulle"
MOD_JEM_CAL_SHOW_TOOLTIPS_CATEGORY_DESC="Afficher la ou les catégories d'événements dans les infobulles."
MOD_JEM_CAL_SHOW_TOOLTIPS_VENUE="Afficher lieu dans infobulle"
MOD_JEM_CAL_SHOW_TOOLTIPS_VENUE_DESC="Afficher le lieu des événements dans les infobulles."
MOD_JEM_CAL_DAYNAME_LENGTH="Longueur intitulés des jours"
MOD_JEM_CAL_DAYNAME_LENGTH_DESC="Choisir d'afficher l'intitulé complet du jour ou la version courte."
MOD_JEM_CAL_DAYNAME_DONT_DISPLAY="Ne pas afficher"
MOD_JEM_CAL_DAYNAME_ONE_LETTER="1 caractère"
MOD_JEM_CAL_DAYNAME_TWO_LETTERS="2 caractères"
MOD_JEM_CAL_DAYNAME_THREE_LETTERS="3 caractères"
MOD_JEM_CAL_DAYNAME_FULL="Intitulé complet"
MOD_JEM_CAL_FIRST_DAY_OF_WEEK="Commencer la semaine le"
MOD_JEM_CAL_FIRST_DAY_OF_WEEK_DESC="Sélectionner le premier jour de la semaine."
MOD_JEM_CAL_YEAR_LENGTH="Longueur année"
MOD_JEM_CAL_YEAR_LENGTH_DESC="Choisir d'afficher 2 ou 4 chiffres."
MOD_JEM_CAL_TWO_DIGITS="2 chiffres"
MOD_JEM_CAL_FOUR_DIGITS="4 chiffres"
MOD_JEM_CAL_SHORT_MONTHNAME="Noms des mois courts"
MOD_JEM_CAL_SHORT_MONTHNAME_DESC="Choisir d'afficher le nom abrégé ou complet des mois."
MOD_JEM_CAL_MONTH_OFFSET="Décalage mois"
MOD_JEM_CAL_MONTH_OFFSET_DESC="Définir le mois par défaut. Au lieu du mois en cours (décalage 0), le mois prochain (décalage 1) ou le mois précédent (décalage -1) seront affichés."
MOD_JEM_CAL_TIME_OFFSET="Décalage heure"
MOD_JEM_CAL_TIME_OFFSET_DESC="Utilisez cette option UNIQUEMENT si vous devez décaler l'heure par rapport aux paramètres du serveur."
MOD_JEM_CAL_REMEMBER="Se souvenir"
MOD_JEM_CAL_REMEMBER_DESC="Se souvenir du mois/année sélectionné lors du changement de page, sans retourner au mois en cours."
MOD_JEM_CAL_USE_AJAX="Utiliser AJAX"
MOD_JEM_CAL_USE_AJAX_DESC="Si défini sur Oui, la navigation mensuelle demandera uniquement le contenu du module au lieu de recharger la page complète. Il reviendra également au rechargement complet de la page si Javascript est désactivé sur le navigateur de l'utilisateur."
MOD_JEM_CAL_SHOW_CURRENT_EVENTS="Afficher les événements actuels"
MOD_JEM_CAL_SHOW_CURRENT_EVENTS_DESC="Afficher les événements actuels. Ne mets pas à la fois ceci et Afficher les événements archivés sur Non, sinon AUCUN événement ne sera affiché."
MOD_JEM_CAL_SHOW_ARCHIVED_EVENTS="Afficher les événements archivés"
MOD_JEM_CAL_SHOW_ARCHIVED_EVENTS_DESC="Afficher les événements archivés. Ne mets pas à la fois ceci et Afficher les événements actuels sur Non, sinon AUCUN événement ne sera affiché."
MOD_JEM_CAL_LIMIT_TO_CATEGORY_IDS="Limiter aux catégories"
MOD_JEM_CAL_LIMIT_TO_CATEGORY_IDS_DESC="Afficher un calendrier uniquement pour la ou les catégories choisies. Laisse vide pour aucune limitation."
MOD_JEM_CAL_LIMIT_TO_VENUE_IDS="Limiter aux lieux"
MOD_JEM_CAL_LIMIT_TO_VENUE_IDS_DESC="Afficher un calendrier uniquement pour le ou les lieux choisis. Laisse vide pour aucune limitation."
MOD_JEM_CAL_STRAIGHT_TO_DETAILS="Aller directement aux détails"
MOD_JEM_CAL_STRAIGHT_TO_DETAILS_DESC="Aller directement à la page de détails lorsqu'il n'y a qu'un seul événement à choisir."
MOD_JEM_CAL_DEFAULT_CSS="Utiliser le CSS par défaut"
MOD_JEM_CAL_DEFAULT_CSS_DESC="Utiliser la feuille de style par défaut modules/mod_jem_cal/mod_jemcal.css"
MOD_JEM_CAL_USER_CSS="Utiliser un CSS alternatif"
MOD_JEM_CAL_USER_CSS_DESC="Utiliser une feuille de style alternative, par exemple modules/mod_jem_cal/mystylesheet.css. Remplis le chemin complet vers ton fichier css, comme dans l'exemple !"
MOD_JEM_CAL_MODULE_CLASS_SUFFIX="Suffixe de classe du module"
MOD_JEM_CAL_MODULE_CLASS_SUFFIX_DESC="Un suffixe à appliquer à la classe CSS du module (table.moduletable), cela permet un style de module individuel."
MOD_JEM_CAL_DEFAULT_ITEM_ID="ID d'élément de menu par défaut"
MOD_JEM_CAL_DEFAULT_ITEM_ID_DESC="Remplacer l'ItemID utilisé lorsque le lien du calendrier va directement aux détails par un élément de menu de ton choix."
MOD_JEM_CAL_EVENT="Événement"
MOD_JEM_CAL_EVENTS="Événements"
MOD_JEM_CAL_CACHING="Mise en cache"
MOD_JEM_CAL_CACHING_DESC="Sélectionne si tu veux mettre en cache le contenu de ce module."
MOD_JEM_CAL_CACHE_TIME="Durée du cache"
MOD_JEM_CAL_CACHE_TIME_DESC="Le délai avant que le module ne soit à nouveau mis en cache."
; Module intro and footer text
MOD_JEM_CAL_MODULE_TEXT_BLOCK="Introduction et pied de page du module"
MOD_JEM_CAL_SHOW_INTROTEXT="Afficher le texte d'introduction"
MOD_JEM_CAL_SHOW_INTROTEXT_DESC="Affiche un texte personnalisé au-dessus du contenu du module."
MOD_JEM_CAL_INTROTEXT="Texte d'introduction"
MOD_JEM_CAL_INTROTEXT_DESC="Texte affiché au-dessus du contenu du module."
MOD_JEM_CAL_SHOW_FOOTERTEXT="Afficher le texte de pied de page"
MOD_JEM_CAL_SHOW_FOOTERTEXT_DESC="Affiche un texte personnalisé en dessous du contenu du module."
MOD_JEM_CAL_FOOTERTEXT="Texte de pied de page"
MOD_JEM_CAL_FOOTERTEXT_DESC="Texte affiché en dessous du contenu du module."

