; @package    JEM
; @subpackage JEM Jubilee Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2005-2009 Christoph Lukes
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_JUBILEE_EVENTS_IN_MODULE="Événements dans le module"
MOD_JEM_JUBILEE_EVENTS_IN_MODULE_DESC="Nombre d'événements affichés dans le module."
MOD_JEM_JUBILEE_SHOW_NO_EVENTS="Afficher 'Aucun événement'"
MOD_JEM_JUBILEE_SHOW_NO_EVENTS_DESC="Afficher un texte si aucun événement n'est trouvé. Sinon le module ne sera pas affiché."
MOD_JEM_JUBILEE_PUBLISHING_STATE="État de publication"
MOD_JEM_JUBILEE_PUBLISHING_STATE_DESC="Sélectionne si tu veux afficher les événements archivés, les événements publiés, ou les deux. Si tu laisses JEM archiver les anciens événements, tu peux décider ici entre \\"_QQ_\"Événements d'aujourd'hui\\"_QQ_\" (publiés) et \\"_QQ_\"Événements anniversaires\\"_QQ_\" (archivés)."
MOD_JEM_JUBILEE_PUBLISHED_EVENTS="Événements publiés"
MOD_JEM_JUBILEE_ARCHIVED_EVENTS="Événements archivés"
MOD_JEM_JUBILEE_BOTH_EVENTS="Les deux"
MOD_JEM_JUBILEE_OFFSET_DAYS="Décalage de jours"
MOD_JEM_JUBILEE_OFFSET_DAYS_DESC="Déplace la date vers le futur (valeurs positives) ou vers le passé (valeurs négatives)."
MOD_JEM_JUBILEE_DATE_MATCH_MODE="Mode de correspondance de date"
MOD_JEM_JUBILEE_DATE_MATCH_MODE_DESC="Afficher les événements s'étendant sur plusieurs jours si le jour et le mois correspondent à leur date de début, à leur date de fin, à l'une ou l'autre de ces dates, ou à n'importe quelle date comprise entre la date de début et la date de fin. Pour les événements d'une seule journée, il n'y a aucune différence."
MOD_JEM_JUBILEE_SHOW_PAST_YEAR_EVENTS="Inclure les années passées"
MOD_JEM_JUBILEE_SHOW_PAST_YEAR_EVENTS_DESC="Si vous choisissez « OUI », les événements des années précédentes seront inclus."
MOD_JEM_JUBILEE_DATE_MATCH_FROM_START_TO_END="À tout moment entre la date de début et la date de fin"
MOD_JEM_JUBILEE_DATE_MATCH_ON_START="Exactement à la date de début"
MOD_JEM_JUBILEE_DATE_MATCH_ON_END="Exactement à la date de fin"
MOD_JEM_JUBILEE_DATE_MATCH_ON_START_OR_END="Exactement à la date de début ou de fin"
MOD_JEM_JUBILEE_VENUE="Lieu"
MOD_JEM_JUBILEE_MAX_TITLE_LENGTH="Longueur max. du titre"
MOD_JEM_JUBILEE_MAX_TITLE_LENGTH_DESC="Longueur max. du titre."
MOD_JEM_JUBILEE_LINK_TO_DETAILS="Lien vers l'événement sur le titre"
MOD_JEM_JUBILEE_LINK_TO_DETAILS_DESC="Lien vers la page de l'événement sur le titre."
MOD_JEM_JUBILEE_EVENT_LINK_EVENT_LAYOUT="Disposition du bloc événement"
MOD_JEM_JUBILEE_EVENT_LINK_EVENT_LAYOUT_DESC="Force facultativement la disposition du bloc événement lors de l'ouverture d'un événement depuis ce module."
MOD_JEM_JUBILEE_EVENT_LINK_VENUE_LAYOUT="Disposition du bloc lieu"
MOD_JEM_JUBILEE_EVENT_LINK_VENUE_LAYOUT_DESC="Force facultativement la disposition du bloc lieu lors de l'ouverture d'un événement depuis ce module."
MOD_JEM_JUBILEE_EVENT_LINK_LAYOUT_DETAILS="Détails"
MOD_JEM_JUBILEE_EVENT_LINK_LAYOUT_COMPACT="Compact"
MOD_JEM_JUBILEE_SHOWDESC="Afficher la description"
MOD_JEM_JUBILEE_SHOWDESC_DESC="Afficher ou masquer la description de l'événement"
MOD_JEM_JUBILEE_SHOWFLYER="Afficher l'affiche"
MOD_JEM_JUBILEE_SHOWFLYER_DESC="Afficher ou masquer l'image de l'événement."
MOD_JEM_JUBILEE_SHOWVENUE="Afficher le lieu"
MOD_JEM_JUBILEE_SHOWVENUE_DESC="Afficher ou masquer le lieu."
MOD_JEM_JUBILEE_SHOWCATEGORY="Afficher la catégorie"
MOD_JEM_JUBILEE_SHOWCATEGORY_DESC="Afficher ou masquer la catégorie."
MOD_JEM_JUBILEE_LINK_TO_CATEGORY="Lien vers la catégorie"
MOD_JEM_JUBILEE_LINK_TO_CATEGORY_DESC="Lien vers la catégorie. Seulement si Afficher la catégorie a été choisi ci-dessus !"
MOD_JEM_JUBILEE_LINK_TO_VENUE="Lien vers le lieu"
MOD_JEM_JUBILEE_LINK_TO_VENUE_DESC="Lien vers le lieu. Seulement si Afficher le lieu a été choisi ci-dessus !"
MOD_JEM_JUBILEE_FLYER_LINKS_TO="L'affiche renvoie vers..."
MOD_JEM_JUBILEE_FLYER_LINKS_TO_DESC="Un clic sur l'image de l'affiche affichera l'image en taille originale sur une page complète, dans une fenêtre modale popup, ou ouvrira la vue détaillée de l'événement. Ce paramètre nécessite que Afficher l'affiche soit défini sur Oui."
MOD_JEM_JUBILEE_FLYER_LINK_IMAGE_PAGE="Image sur page complète"
MOD_JEM_JUBILEE_FLYER_LINK_IMAGE_MODAL="Image dans fenêtre modale"
MOD_JEM_JUBILEE_FLYER_LINK_EVENT_DETAILS="Vue détaillée de l'événement"
MOD_JEM_JUBILEE_DATE="Date"
MOD_JEM_JUBILEE_CATEGORY_ID="Catégories"
MOD_JEM_JUBILEE_CATEGORY_ID_DESC="Choisis des catégories pour limiter la sortie à celles-ci. Laisse vide si tu veux afficher tous les événements."
MOD_JEM_JUBILEE_VENUE_ID="Lieux"
MOD_JEM_JUBILEE_VENUE_ID_DESC="Choisis des lieux pour limiter la sortie à ceux-ci. Laisse vide si tu veux afficher tous les événements."
MOD_JEM_JUBILEE_STATE="Comté"
MOD_JEM_JUBILEE_STATE_DESC="Saisissez les départements séparés par des virgules pour limiter les événements à ceux sélectionnés. Laissez ce champ vide pour afficher les événements de tous les départements."
MOD_JEM_JUBILEE_STATE_MODE="Mode de correspondance du comté"
MOD_JEM_JUBILEE_STATE_MODE_DESC="Sélectionne si le comté doit correspondre complètement à l'une des chaînes données ci-dessus, ou seulement en contenir une."
MOD_JEM_JUBILEE_STATE_MODE_EXACTMATCH="Correspondance complète"
MOD_JEM_JUBILEE_STATE_MODE_CONTAINS="Contient"
MOD_JEM_JUBILEE_SHOW_DATE_OR_YEAR_DIFFERENCE="Type d'affichage de la date"
MOD_JEM_JUBILEE_SHOW_DATE_OR_YEAR_DIFFERENCE_DESC="Sélectionne pour masquer la date ou afficher la date formatée ou la différence en années du jour actuel à la date de l'événement."
MOD_JEM_JUBILEE_HIDE_DATE="Masquer la date"
MOD_JEM_JUBILEE_SHOW_DATE="Afficher la date"
MOD_JEM_JUBILEE_SHOW_YEAR_DIFFERENCE="Afficher la différence d'années"
MOD_JEM_JUBILEE_DATE_FORMAT="Format de date"
MOD_JEM_JUBILEE_DATE_FORMAT_DESC="Format de date utilisant le format de date PHP, par exemple : « j. M Y ». Pour plus d'informations, <a href=\\« https://www.php.net/manual/fr/datetime.format.php\\ » target=\\« _blank\\ »>consultez le manuel PHP</a>.\n"
MOD_JEM_JUBILEE_SHOWTIME="Afficher l'heure"
MOD_JEM_JUBILEE_SHOWTIME_DESC="Afficher ou masquer l'heure."
MOD_JEM_JUBILEE_TIME_FORMAT="Format d'heure"
MOD_JEM_JUBILEE_TIME_FORMAT_DESC="Format d'heure utilisant le format d'heure PHP, par exemple : \\"_QQ_\"H:i\\"_QQ_\". Pour plus d'informations <a href=\\"_QQ_\"https://www.php.net/manual/fr/datetime.format.php\\"_QQ_\" target=\\"_QQ_\"_blank\\"_QQ_\">visite le manuel PHP</a>."
MOD_JEM_JUBILEE_MODULE_CLASS_SUFFIX="Suffixe de classe du module"
MOD_JEM_JUBILEE_MODULE_CLASS_SUFFIX_DESC="Un suffixe à appliquer à la classe CSS du module, cela permet un style de module individuel."
MOD_JEM_JUBILEE_CACHING="Mise en cache"
MOD_JEM_JUBILEE_CACHING_DESC="Sélectionne si tu veux mettre en cache le contenu de ce module."
MOD_JEM_JUBILEE_CACHE_TIME="Durée du cache"
MOD_JEM_JUBILEE_CACHE_TIME_DESC="Le délai avant que le module ne soit à nouveau mis en cache."
MOD_JEM_JUBILEE_ALLOW_LINEBREAK="Autoriser les sauts de ligne"
MOD_JEM_JUBILEE_ALLOW_LINEBREAK_DESC="Autoriser les sauts de ligne ou les remplacer par un espace."
MOD_JEM_JUBILEE_MAX_DESCRIPTION_LENGTH="Longueur max. de la description"
MOD_JEM_JUBILEE_MAX_DESCRIPTION_LENGTH_DESC="Limiter la description affichée à ce nombre de caractères."
MOD_JEM_JUBILEE_FIELD_READMORE_DESC="Si l'option est réglée sur « Oui », le lien « Lire la suite… » s'affichera si la description de l'événement comporte un saut de ligne « Lire la suite ».\n"
MOD_JEM_JUBILEE_FIELD_READMORE_LABEL="Lien 'Lire la suite...'"
MOD_JEM_JUBILEE_SHOW_MORE_INFORMATION="Afficher Plus d'informations"
MOD_JEM_JUBILEE_SHOW_MORE_INFORMATION_DESC="Afficher un lien ou un bouton « Plus d'informations » lorsque l'événement est associé à un article."
MOD_JEM_JUBILEE_SHOW_MORE_INFORMATION_TITLE="Afficher plus d'informations Titre"
MOD_JEM_JUBILEE_SHOW_MORE_INFORMATION_TITLE_DESC="Afficher le titre de l'article correspondant après le texte du lien « Plus d'informations »."
MOD_JEM_JUBILEE_READMORE_LINK="Oui (lien)"
MOD_JEM_JUBILEE_READMORE_BUTTON="Oui (bouton)"
MOD_JEM_JUBILEE_MORE_INFORMATION_LINK="Oui (lien)"
MOD_JEM_JUBILEE_MORE_INFORMATION_BUTTON="Oui (bouton)"
MOD_JEM_JUBILEE_SHOWCALENDAR="Afficher le calendrier"
MOD_JEM_JUBILEE_SHOWCALENDAR_DESC="Affiche une image de calendrier avec le jour et le mois pour lesquels le module recherche des événements."
MOD_JEM_JUBILEE_COLOR="Couleur"
MOD_JEM_JUBILEE_COLOR_DESC="Couleur de l'image du calendrier. Si \\"_QQ_\"défini par l'utilisateur\\"_QQ_\" est choisi, la valeur de couleur sera prise du champ ci-dessous."
MOD_JEM_JUBILEE_BLUE="Bleu"
MOD_JEM_JUBILEE_GREEN="Vert"
MOD_JEM_JUBILEE_ORANGE="Orange"
MOD_JEM_JUBILEE_RED="Rouge"
MOD_JEM_JUBILEE_USER="défini par l'utilisateur"
MOD_JEM_JUBILEE_USER_COLOR="Couleur utilisateur"
MOD_JEM_JUBILEE_USER_COLOR_DESC="Couleur utilisée si \\"_QQ_\"défini par l'utilisateur\\"_QQ_\" est choisi ci-dessus."
MOD_JEM_JUBILEE_SHUFFLE="Mélanger les événements"
MOD_JEM_JUBILEE_SHUFFLE_DESC="S'il y a plus d'événements à afficher, choisir aléatoirement des événements dans le pool."
MOD_JEM_JUBILEE_SHUFFLE_COUNT="Limite du pool de mélange"
MOD_JEM_JUBILEE_SHUFFLE_COUNT_DESC="Limite les événements lus de la base de données par un montant max., mais sera corrigé à au moins le nombre d'événements à afficher."
MOD_JEM_JUBILEE_INTROTEXT="Texte d'introduction"
MOD_JEM_JUBILEE_INTROTEXT_DESC="Texte affiché au-dessus des événements juste à côté de l'image du calendrier. Les bbCodes supportés sont [day], [month], [year]. Laisse vide pour ne pas afficher de texte d'introduction."
MOD_JEM_JUBILEE_ORDER="Ordre des événements"
MOD_JEM_JUBILEE_ORDER_DESC="L'ordre dans lequel les événements seront affichés."
MOD_JEM_JUBILEE_ORDER_ASCENDING="Date croissante"
MOD_JEM_JUBILEE_ORDER_DESCENDING="Date décroissante"
MOD_JEM_JUBILEE="JEM - Module-Jubilé"
MOD_JEM_JUBILEE_XML_DESCRIPTION="Module JEM des événements anniversaires Jubilé."

; Frontend
MOD_JEM_JUBILEE_TODAY="Aujourd'hui"
MOD_JEM_JUBILEE_TOMORROW="Demain"
MOD_JEM_JUBILEE_YESTERDAY="Hier"
MOD_JEM_JUBILEE_FROM="Du %s"
MOD_JEM_JUBILEE_UNTIL="Jusqu'au %s"
MOD_JEM_JUBILEE_FROM_UNTIL="Du %s au %s"
MOD_JEM_JUBILEE_ON_DATE="Le %s"
MOD_JEM_JUBILEE_READMORE="Lire la suite..."
MOD_JEM_JUBILEE_MORE_INFORMATION="Plus d'informations"
MOD_JEM_JUBILEE_READMORE_REGISTER="Connecte-toi pour lire plus de détails."
MOD_JEM_JUBILEE_NO_DESCRIPTION=""
MOD_JEM_JUBILEE_NO_EVENTS="Aucun événement trouvé."
MOD_JEM_JUBILEE_YEAR_AGO="Il y a %s an"
MOD_JEM_JUBILEE_YEARS_AGO="Il y a %s ans"
MOD_JEM_JUBILEE_NEARLY_YEAR_AGO="Il y a presque %s an"
MOD_JEM_JUBILEE_NEARLY_YEARS_AGO="Il y a presque %s ans"
MOD_JEM_JUBILEE_OVER_YEAR_AGO="Il y a plus de %s an"
MOD_JEM_JUBILEE_OVER_YEARS_AGO="Il y a plus de %s ans"
MOD_JEM_JUBILEE_MONTHS_AGO="Il y a %s mois"
MOD_JEM_JUBILEE_DAYS_AGO="Il y a %s jours"
MOD_JEM_JUBILEE_YEAR_AHEAD="%s an d'avance"
MOD_JEM_JUBILEE_YEARS_AHEAD="%s ans d'avance"
MOD_JEM_JUBILEE_NEARLY_YEAR_AHEAD="Presque %s an d'avance"
MOD_JEM_JUBILEE_NEARLY_YEARS_AHEAD="Presque %s ans d'avance"
MOD_JEM_JUBILEE_OVER_YEAR_AHEAD="Plus de %s an d'avance"
MOD_JEM_JUBILEE_OVER_YEARS_AHEAD="Plus de %s ans d'avance"
MOD_JEM_JUBILEE_MONTHS_AHEAD="%s mois d'avance"
MOD_JEM_JUBILEE_DAYS_AHEAD="%s jours d'avance"
MOD_JEM_JUBILEE_DAYS_LEFT="%s jours avant"
MOD_JEM_JUBILEE_ENDED_YEAR_AGO="Terminé il y a %s an"
MOD_JEM_JUBILEE_ENDED_YEARS_AGO="Terminé il y a %s ans"
MOD_JEM_JUBILEE_ENDED_NEARLY_YEAR_AGO="Terminé il y a presque %s an"
MOD_JEM_JUBILEE_ENDED_NEARLY_YEARS_AGO="Terminé il y a presque %s ans"
MOD_JEM_JUBILEE_ENDED_OVER_YEAR_AGO="Terminé il y a plus de %s an"
MOD_JEM_JUBILEE_ENDED_OVER_YEARS_AGO="Terminé il y a plus de %s ans"
MOD_JEM_JUBILEE_ENDED_DAY_AGO="Terminé il y a %s jour"
MOD_JEM_JUBILEE_ENDED_DAYS_AGO="Terminé il y a %s jours"
MOD_JEM_JUBILEE_STARTED_YEAR_AGO="Commencé il y a %s an"
MOD_JEM_JUBILEE_STARTED_YEARS_AGO="Commencé il y a %s ans"
MOD_JEM_JUBILEE_STARTED_NEARLY_YEAR_AGO="Commencé il y a presque %s an"
MOD_JEM_JUBILEE_STARTED_NEARLY_YEARS_AGO="Commencé il y a presque %s ans"
MOD_JEM_JUBILEE_STARTED_OVER_YEAR_AGO="Commencé il y a plus de %s an"
MOD_JEM_JUBILEE_STARTED_OVER_YEARS_AGO="Commencé il y a plus de %s ans"
MOD_JEM_JUBILEE_STARTED_DAYS_AGO="Commencé il y a %s jours"
; Module intro and footer text
MOD_JEM_JUBILEE_MODULE_TEXT_BLOCK="Introduction et pied de page du module"
MOD_JEM_JUBILEE_SHOW_INTROTEXT="Afficher le texte d'introduction"
MOD_JEM_JUBILEE_SHOW_INTROTEXT_DESC="Affiche un texte personnalisé au-dessus du contenu du module."
MOD_JEM_JUBILEE_SHOW_FOOTERTEXT="Afficher le texte de pied de page"
MOD_JEM_JUBILEE_SHOW_FOOTERTEXT_DESC="Affiche un texte personnalisé en dessous du contenu du module."
MOD_JEM_JUBILEE_FOOTERTEXT="Texte de pied de page"
MOD_JEM_JUBILEE_FOOTERTEXT_DESC="Texte affiché en dessous du contenu du module."

