; JEM Types Module - sys.ini
MOD_JEM_TYPES="JEM - Types"
MOD_JEM_TYPES_XML_DESCRIPTION="Affiche une liste de types d'événements avec le nombre d'événements ou les événements les plus à venir par type."
MOD_JEM_TYPES_EVENT_LINK_EVENT_LAYOUT="Disposition du bloc événement"
MOD_JEM_TYPES_EVENT_LINK_EVENT_LAYOUT_DESC="Forcer éventuellement la disposition du bloc événement lors de l'ouverture d'un événement à partir de ce module."
MOD_JEM_TYPES_EVENT_LINK_VENUE_LAYOUT="Disposition du bloc de la salle"
MOD_JEM_TYPES_EVENT_LINK_VENUE_LAYOUT_DESC="Forcer éventuellement la disposition du bloc de lieu lors de l'ouverture d'un événement à partir de ce module."
MOD_JEM_TYPES_EVENT_LINK_LAYOUT_DETAILS="Détails du produit"
MOD_JEM_TYPES_EVENT_LINK_LAYOUT_COMPACT="Compact"
; Module intro and footer text
MOD_JEM_TYPES_MODULE_TEXT_BLOCK="Introduction du module et pied de page"
MOD_JEM_TYPES_SHOW_INTROTEXT="Afficher le texte d'introduction"
MOD_JEM_TYPES_SHOW_INTROTEXT_DESC="Afficher le texte personnalisé au-dessus du contenu du module."
MOD_JEM_TYPES_INTROTEXT="Texte d'introduction"
MOD_JEM_TYPES_INTROTEXT_DESC="Texte affiché au-dessus du contenu du module."
MOD_JEM_TYPES_SHOW_FOOTERTEXT="Afficher le texte du pied de page"
MOD_JEM_TYPES_SHOW_FOOTERTEXT_DESC="Afficher le texte personnalisé sous le contenu du module."
MOD_JEM_TYPES_FOOTERTEXT="Texte de pied de page"
MOD_JEM_TYPES_FOOTERTEXT_DESC="Texte affiché sous le contenu du module."

