; @package    JEM
; @subpackage JEM Upcoming Events Basic Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2005-2009 Christoph Lukes
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_EVENTS_IN_MODULE="Événements en module"
MOD_JEM_EVENTS_IN_MODULE_DESC="Nombre d'événements affichés dans le module"
MOD_JEM_UPCOMING_OR_ARCHIVED="Type d'affichage des événements"
MOD_JEM_UPCOMING_OR_ARCHIVED_DESC="Choisissez entre les événements à venir, en cours ou archivés."
MOD_JEM_UPCOMING_EVENTS="Événements à venir"
MOD_JEM_UNFINISHED_EVENTS="Événements en cours"
MOD_JEM_ARCHIVED_EVENTS="Événements archivés"
MOD_JEM_SHOW_NO_EVENTS="Afficher 'aucun événement'"
MOD_JEM_SHOW_NO_EVENTS_DESC="Afficher un texte si aucun événement n'est trouvé. Sinon le module ne sera pas affiché."
MOD_JEM_HIGHLIGHT_FEATURED="Mettre en évidence les événements en vedette"
MOD_JEM_HIGHLIGHT_FEATURED_DESC="Afficher un style particulier pour les événements en vedette en gras par défaut."
MOD_JEM_OFFSET_HOURS="Décalage horaire (en heures)"
MOD_JEM_OFFSET_HOURS_DESC="Déplace le temps vers le futur (valeurs positives) ou vers le passé (valeurs négatives). Utilisé uniquement pour afficher les événements non archivés. <br>Exemples : pour afficher les événements terminés depuis au moins deux heures, définissez le type sur Événements non terminés et le décalage sur -2. Pour afficher les événements commençant dans une semaine ou plus tard, définissez le type sur Événements à venir et le décalage sur 168 (7 * 24)."
MOD_JEM_DISPLAY_ORDER="Ordre d'affichage"
MOD_JEM_DISPLAY_ORDER_DESC="Sélectionner l'ordre pour titre, date et lieu."
MOD_JEM_ORDER_TDV="Titre, Date, Lieu"
MOD_JEM_ORDER_TVD="Titre, Lieu, Date"
MOD_JEM_ORDER_VTD="Lieu, Titre, Date"
MOD_JEM_ORDER_VDT="Lieu, Date, Titre"
MOD_JEM_ORDER_DTV="Date, Titre, Lieu"
MOD_JEM_ORDER_DVT="Date, Lieu, Titre"
MOD_JEM_TITLE_EVENT="Afficher le titre ou le lieu"
MOD_JEM_TITLE_EVENT_DESC="Choisissez si le titre de l'événement doit être affiché."
MOD_JEM_VENUE="Titre du lieu"
MOD_JEM_TITLE="Titre"
MOD_JEM_MAX_TITLE_LENGTH="Longueur maxi du titre"
MOD_JEM_MAX_TITLE_LENGTH_DESC="Longueur maximale u titre"
MOD_JEM_LINK_TO_VENUE="Lien vers le lieu"
MOD_JEM_LINK_TO_VENUE_DESC="Lien vers le lieu. Uniquement si le lieu a été sélectionné ci-dessus."
MOD_JEM_SHOW_CATEGORY="Afficher la catégorie"
MOD_JEM_SHOW_CATEGORY_DESC="Afficher ou masquer la catégorie de l'événement"
MOD_JEM_LINK_TO_CATEGORY="Lien vers la catégorie"
MOD_JEM_LINK_TO_CATEGORY_DESC="Ajouter un lien vers la catégorie de l'événement lorsqu'elle s'affiche."
MOD_JEM_LINK_TO_EVENT="Lien sur l'événement"
MOD_JEM_LINK_TO_EVENT_DESC="Lien sur la page de l'événement pour la date ou le titre (si activé)."
MOD_JEM_EVENT_LINK_EVENT_LAYOUT="Disposition du bloc événement"
MOD_JEM_EVENT_LINK_EVENT_LAYOUT_DESC="Force facultativement la disposition du bloc événement lors de l'ouverture d'un événement depuis ce module."
MOD_JEM_EVENT_LINK_VENUE_LAYOUT="Disposition du bloc lieu"
MOD_JEM_EVENT_LINK_VENUE_LAYOUT_DESC="Force facultativement la disposition du bloc lieu lors de l'ouverture d'un événement depuis ce module."
MOD_JEM_EVENT_LINK_LAYOUT_DETAILS="Détails"
MOD_JEM_EVENT_LINK_LAYOUT_COMPACT="Compact"
MOD_JEM_SHOW_MORE_INFORMATION="Afficher Plus d'informations"
MOD_JEM_SHOW_MORE_INFORMATION_DESC="Afficher un lien ou un bouton « Plus d'informations » lorsque l'événement est associé à un article."
MOD_JEM_SHOW_MORE_INFORMATION_TITLE="Afficher plus d'informations Titre"
MOD_JEM_SHOW_MORE_INFORMATION_TITLE_DESC="Afficher le titre de l'article correspondant après le texte du lien « Plus d'informations »."
MOD_JEM_MORE_INFORMATION_LINK="Oui (lien)"
MOD_JEM_MORE_INFORMATION_BUTTON="Oui (bouton)"
MOD_JEM_SHOW_ICON_COUNTRY_VENUE="Afficher l'icône du pays"
MOD_JEM_SHOW_ICON_COUNTRY_VENUE_DESC="Afficher la petite icône du pays où se déroule chaque événement."
MOD_JEM_SHOW_FLAG_ICON="Icône de drapeau"
MOD_JEM_DATE="Date"
MOD_JEM_CATEGORY_ID="Catégories"
MOD_JEM_CATEGORY_ID_DESC="Choisissez des catégories auxquelles limiter l'affichage. Laissez à vide si vous souhaitez afficher tous les événements."
MOD_JEM_VENUE_ID="Lieux"
MOD_JEM_VENUE_ID_DESC="Choisissez des lieux auxquels limiter l'affichage. Laissez vide si vous souhaitez afficher tous les événements."
MOD_JEM_DATE_FORMAT="Format de date"
MOD_JEM_DATE_FORMAT_DESC="Format de date utilisant le format de date PHP, par exemple : « j. M Y ». Pour plus d'informations, <a href=\\« https://www.php.net/manual/fr/datetime.format.php\\ » target=\\« _blank\\ »>consultez le manuel PHP</a>.\n"
MOD_JEM_TIME_FORMAT="Format de l'heure"
MOD_JEM_TIME_FORMAT_DESC="Format de temps utilisant le format de temps PHP, par exemple : « H:i ». Pour plus d'informations, <a href=\\« https://www.php.net/manual/fr/datetime.format.php\\ » target=\\« _blank\\ »>consultez le manuel PHP</a>."
MOD_JEM_MODULE_CLASS_SUFFIX="Suffixe de classe du module"
MOD_JEM_MODULE_CLASS_SUFFIX_DESC="Un suffixe devant être appliqué à la classe CSS du module. Ceci vous permet de styliser individuellement chaque module."
MOD_JEM_CACHING="Cache"
MOD_JEM_CACHING_DESC="Choisissez s'il faut activer le cache de contenu de ce module"
MOD_JEM_NO_CACHING="Pas de cache"
MOD_JEM_CACHE_TIME="Durée du cache"
MOD_JEM_CACHE_TIME_DESC="Le délai avant que le module ne soit à nouveau mis en cache."
MOD_JEM="JEM - Module-Basic"
MOD_JEM_XML_DESCRIPTION="JEM Basic Module <br>Affiche les événements dans une position de module"

; Frontend
MOD_JEM_NO_EVENTS="Aucun événement ici"
MOD_JEM_MORE_INFORMATION="Plus d'informations"
MOD_JEM_ALL_DAY="Toute la journée"
; Module intro and footer text
MOD_JEM_MODULE_TEXT_BLOCK="Introduction et pied de page du module"
MOD_JEM_SHOW_INTROTEXT="Afficher le texte d'introduction"
MOD_JEM_SHOW_INTROTEXT_DESC="Affiche un texte personnalisé au-dessus du contenu du module."
MOD_JEM_INTROTEXT="Texte d'introduction"
MOD_JEM_INTROTEXT_DESC="Texte affiché au-dessus du contenu du module."
MOD_JEM_SHOW_FOOTERTEXT="Afficher le texte de pied de page"
MOD_JEM_SHOW_FOOTERTEXT_DESC="Affiche un texte personnalisé en dessous du contenu du module."
MOD_JEM_FOOTERTEXT="Texte de pied de page"
MOD_JEM_FOOTERTEXT_DESC="Texte affiché en dessous du contenu du module."

