; @package    JEM
; @subpackage JEM Latest Events Wide Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2005-2009 Christoph Lukes
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_WIDE_EVENTS_IN_MODULE="Arrangementer i modulen"
MOD_JEM_WIDE_EVENTS_IN_MODULE_DESC="Antall arrangementer vist i modulen."
MOD_JEM_WIDE_UPCOMING_ARCHIVED_OR_CURRENT="Visningstype for arrangementer"
MOD_JEM_WIDE_UPCOMING_ARCHIVED_OR_CURRENT_DESC="Velg om du vil vise kommende, ikke-fullførte, arkiverte eller dagens arrangementer."
MOD_JEM_WIDE_UPCOMING_EVENTS="Kommende"
MOD_JEM_WIDE_UNFINISHED_EVENTS="Ikke-fullførte"
MOD_JEM_WIDE_ARCHIVED_EVENTS="Arkiverte"
MOD_JEM_WIDE_CURRENT_EVENTS="I dag"
MOD_JEM_WIDE_SHOW_NO_EVENTS="Vis 'Ingen arrangementer'"
MOD_JEM_WIDE_SHOW_NO_EVENTS_DESC="Vis tekst hvis ingen arrangementer ble funnet. Ellers vil ikke modulen vises."
MOD_JEM_HIGHLIGHT_FEATURED="Uthev utvalgte"
MOD_JEM_HIGHLIGHT_FEATURED_DESC="Vis en spesiell stil for utvalgte arrangementer, som standard fet."
MOD_JEM_WIDE_OFFSET_HOURS="Tidsforskyvning (i timer)"
MOD_JEM_WIDE_OFFSET_HOURS_DESC="Flytter tid inn i fremtiden (positive verdier) eller inn i fortiden (negative verdier). Brukes kun til å vise ikke-arkiverte arrangementer; på dagens arrangementer rundes det av til hele dager. <br>Eksempler: For å vise arrangementer som avsluttet minst to timer siden, sett type til Ikke-fullførte arrangementer og forskyvning til -2. For å vise arrangementer som starter om én uke eller senere, sett type til Kommende arrangementer og forskyvning til 168 (7 * 24). For å vise morgendagens arrangementer, sett type til I dag og forskyvning til 24."
MOD_JEM_WIDE_VENUE="Sted"
MOD_JEM_WIDE_MAX_TITLE_LENGTH="Maks. tittellengde"
MOD_JEM_WIDE_MAX_TITLE_LENGTH_DESC="Maks. lengde på tittelen."
MOD_JEM_WIDE_LINK_TO_EVENT="Lenke til arrangement på tittel"
MOD_JEM_WIDE_LINK_TO_EVENT_DESC="Lenke til arrangementssiden på tittel."
MOD_JEM_WIDE_EVENT_LINK_EVENT_LAYOUT="Oppsett for arrangementsblokk"
MOD_JEM_WIDE_EVENT_LINK_EVENT_LAYOUT_DESC="Valgfritt tving oppsettet for arrangementsblokk når et arrangement åpnes fra denne modulen."
MOD_JEM_WIDE_EVENT_LINK_VENUE_LAYOUT="Oppsett for lokasjonsblokk"
MOD_JEM_WIDE_EVENT_LINK_VENUE_LAYOUT_DESC="Valgfritt tving oppsettet for lokasjonsblokk når et arrangement åpnes fra denne modulen."
MOD_JEM_WIDE_EVENT_LINK_LAYOUT_DETAILS="Detaljer"
MOD_JEM_WIDE_EVENT_LINK_LAYOUT_COMPACT="Kompakt"
MOD_JEM_WIDE_SHOW_MORE_INFORMATION="Vis mer informasjon"
MOD_JEM_WIDE_SHOW_MORE_INFORMATION_DESC="Vis en 'Mer informasjon'-lenke eller -knapp når arrangementet har en tilknyttet artikkel."
MOD_JEM_WIDE_SHOW_MORE_INFORMATION_TITLE="Vis tittel for mer informasjon"
MOD_JEM_WIDE_SHOW_MORE_INFORMATION_TITLE_DESC="Vis den tilknyttede artikkeltittelen etter 'Mer informasjon'-lenketeksten."
MOD_JEM_WIDE_MORE_INFORMATION_LINK="Ja (lenke)"
MOD_JEM_WIDE_MORE_INFORMATION_BUTTON="Ja (knapp)"
MOD_JEM_WIDE_LINK_TO_CATEGORY="Lenke til kategori"
MOD_JEM_WIDE_LINK_TO_CATEGORY_DESC="Lenke til kategorien."
MOD_JEM_WIDE_SHOW_CATEGORY="Vis kategori"
MOD_JEM_WIDE_SHOW_CATEGORY_DESC="Vis eller skjul arrangementskategorien."
MOD_JEM_WIDE_SHOW_VENUE="Vis arrangement"
MOD_JEM_WIDE_SHOW_VENUE_DESC="Vis eller skjul arrangementslokasjonen."
MOD_JEM_WIDE_LINK_TO_VENUE="Lenke til lokasjon"
MOD_JEM_WIDE_LINK_TO_VENUE_DESC="Lenke til lokasjonen."
MOD_JEM_WIDE_USE_MODAL="Modalt vindu"
MOD_JEM_WIDE_USE_MODAL_DESC="Det modale vinduet viser bildet i original størrelse etter et klikk med en fin effekt innenfor gjeldende skjerm"
MOD_JEM_WIDE_DATE="Dato"
MOD_JEM_WIDE_CATEGORY_ID="Kategorier"
MOD_JEM_WIDE_CATEGORY_ID_DESC="Velg kategorier for å begrense utdataene til dem. La stå tomt hvis du vil vise alle arrangementer."
MOD_JEM_WIDE_VENUE_ID="Lokasjoner"
MOD_JEM_WIDE_VENUE_ID_DESC="Velg lokasjoner for å begrense utdataene til dem. La stå tomt hvis du vil vise alle arrangementer."
MOD_JEM_WIDE_SHOW_DATE="Vis dato"
MOD_JEM_WIDE_SHOW_DAY_DIFFERENCE="Vis dagsforskjell"
MOD_JEM_WIDE_SHOW_DATE_OR_DAY_DIFFERENCE="Visningstype for dato"
MOD_JEM_WIDE_SHOW_DATE_OR_DAY_DIFFERENCE_DESC="Velg å vise den formaterte datoen eller dagsforskjellen fra dagens dato til arrangementsdatoen. Merk: Tiden vil bli skjult når dagsforskjell er valgt."
MOD_JEM_WIDE_DATE_FORMAT="Datoformat"
MOD_JEM_WIDE_DATE_FORMAT_DESC="Datoformat som bruker PHP-datoformatet, for eksempel: 'j. M Y'. For mer informasjon <a href='https://www.php.net/manual/en/datetime.format.php' target='_blank'>besøk PHP-manualen</a>."
MOD_JEM_WIDE_TIME_FORMAT="Tidsformat"
MOD_JEM_WIDE_TIME_FORMAT_DESC="Tidsformat som bruker PHP-tidsformatet, for eksempel: 'H:i'. For mer informasjon <a href='https://www.php.net/manual/en/datetime.format.php' target='_blank'>besøk PHP-manualen</a>."
MOD_JEM_WIDE_MODULE_CLASS_SUFFIX="Suffiks for modulklasse"
MOD_JEM_WIDE_MODULE_CLASS_SUFFIX_DESC="Et suffiks som skal brukes på modulens CSS-klasse, dette tillater individuell modulstyling."
MOD_JEM_WIDE_CACHING="Bufring"
MOD_JEM_WIDE_CACHING_DESC="Velg om innholdet i denne modulen skal bufres."
MOD_JEM_WIDE_CACHE_TIME="Bufringstid"
MOD_JEM_WIDE_CACHE_TIME_DESC="Tiden før modulen bufres på nytt."

MOD_JEM_WIDE="JEM - Bredmodul"
MOD_JEM_WIDE_XML_DESCRIPTION="JEM Bredmodul <br>Viser arrangementer i en modulposisjon med bred orientering"
MOD_JEM_WIDE_MORE_INFORMATION="Mer informasjon"

; Frontend
MOD_JEM_WIDE_TODAY="I dag"
MOD_JEM_WIDE_TOMORROW="I morgen"
MOD_JEM_WIDE_YESTERDAY="I går"
MOD_JEM_WIDE_DAYS_AGO="%s dager siden"
MOD_JEM_WIDE_DAYS_AHEAD="%s dager fremover"
MOD_JEM_WIDE_ENDED_DAYS_AGO="Avsluttet %s dager siden"
MOD_JEM_WIDE_STARTED_DAYS_AGO="Startet %s dager siden"
MOD_JEM_WIDE_FROM="Fra %s"
MOD_JEM_WIDE_UNTIL="Til %s"
MOD_JEM_WIDE_FROM_UNTIL="Fra %s til %s"
MOD_JEM_WIDE_ON_DATE="På %s"
MOD_JEM_WIDE_NO_EVENTS="Ingen arrangementer funnet."

; Module intro and footer text
MOD_JEM_WIDE_MODULE_TEXT_BLOCK="Modulens innledningstekst og bunntekst"
MOD_JEM_WIDE_SHOW_INTROTEXT="Vis innledningstekst"
MOD_JEM_WIDE_SHOW_INTROTEXT_DESC="Vis egendefinert tekst over modulens innhold."
MOD_JEM_WIDE_INTROTEXT="Innledningstekst"
MOD_JEM_WIDE_INTROTEXT_DESC="Tekst som vises over modulens innhold."
MOD_JEM_WIDE_SHOW_FOOTERTEXT="Vis bunntekst"
MOD_JEM_WIDE_SHOW_FOOTERTEXT_DESC="Vis egendefinert tekst under modulens innhold."
MOD_JEM_WIDE_FOOTERTEXT="Bunntekst"
MOD_JEM_WIDE_FOOTERTEXT_DESC="Tekst som vises under modulens innhold."