; @package    JEM
; @subpackage JEM Upcoming Events Basic Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2005-2009 Christoph Lukes
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_EVENTS_IN_MODULE="Arrangementer i modulen"
MOD_JEM_EVENTS_IN_MODULE_DESC="Antall arrangementer vist i modulen."
MOD_JEM_UPCOMING_OR_ARCHIVED="Visningstype for arrangementer"
MOD_JEM_UPCOMING_OR_ARCHIVED_DESC="Velg om du vil vise kommende, ikke-fullførte eller arkiverte arrangementer."
MOD_JEM_UPCOMING_EVENTS="Kommende arrangementer"
MOD_JEM_UNFINISHED_EVENTS="Ikke-fullførte arrangementer"
MOD_JEM_ARCHIVED_EVENTS="Arkiverte arrangementer"
MOD_JEM_SHOW_NO_EVENTS="Vis 'Ingen arrangementer'"
MOD_JEM_SHOW_NO_EVENTS_DESC="Vis tekst hvis ingen arrangementer ble funnet. Ellers vil ikke modulen vises."
MOD_JEM_HIGHLIGHT_FEATURED="Uthev utvalgte"
MOD_JEM_HIGHLIGHT_FEATURED_DESC="Vis en spesiell stil for utvalgte arrangementer, som standard fet."
MOD_JEM_OFFSET_HOURS="Tidsforskyvning (i timer)"
MOD_JEM_OFFSET_HOURS_DESC="Flytter tid inn i fremtiden (positive verdier) eller inn i fortiden (negative verdier). Brukes kun til å vise ikke-arkiverte arrangementer. <br>Eksempler: For å vise arrangementer som avsluttet minst to timer siden, sett type til Ikke-fullførte arrangementer og forskyvning til -2. For å vise arrangementer som starter om én uke eller senere, sett type til Kommende arrangementer og forskyvning til 168 (7 * 24)."
MOD_JEM_DISPLAY_ORDER="Visningsrekkefølge"
MOD_JEM_DISPLAY_ORDER_DESC="Velg rekkefølgen for tittel, dato og lokasjon."
MOD_JEM_ORDER_TDV="Tittel, Dato, Lokasjon"
MOD_JEM_ORDER_TVD="Tittel, Lokasjon, Dato"
MOD_JEM_ORDER_VTD="Lokasjon, Tittel, Dato"
MOD_JEM_ORDER_VDT="Lokasjon, Dato, Tittel"
MOD_JEM_ORDER_DTV="Dato, Tittel, Lokasjon"
MOD_JEM_ORDER_DVT="Dato, Lokasjon, Tittel"
MOD_JEM_TITLE_EVENT="Vis tittel eller lokasjon"
MOD_JEM_TITLE_EVENT_DESC="Velg om tittelen på arrangementet skal vises."
MOD_JEM_VENUE="Lokasjonstittel"
MOD_JEM_TITLE="Tittel"
MOD_JEM_MAX_TITLE_LENGTH="Maks. tittellengde"
MOD_JEM_MAX_TITLE_LENGTH_DESC="Maks. lengde på tittelen."
MOD_JEM_LINK_TO_VENUE="Lenke til lokasjon"
MOD_JEM_LINK_TO_VENUE_DESC="Lenke til lokasjonen. Bare hvis Lokasjon er valgt ovenfor!"
MOD_JEM_SHOW_CATEGORY="Vis kategori"
MOD_JEM_SHOW_CATEGORY_DESC="Vis eller skjul arrangementskategorien."
MOD_JEM_LINK_TO_CATEGORY="Lenke til kategori"
MOD_JEM_LINK_TO_CATEGORY_DESC="Lenke arrangementskategorien når den vises."
MOD_JEM_LINK_TO_EVENT="Lenke til arrangement på"
MOD_JEM_LINK_TO_EVENT_DESC="Lenke til arrangementssiden på Dato eller Tittel (hvis aktivert)."
MOD_JEM_EVENT_LINK_EVENT_LAYOUT="Oppsett for arrangementsblokk"
MOD_JEM_EVENT_LINK_EVENT_LAYOUT_DESC="Valgfritt tving oppsettet for arrangementsblokk når et arrangement åpnes fra denne modulen."
MOD_JEM_EVENT_LINK_VENUE_LAYOUT="Oppsett for lokasjonsblokk"
MOD_JEM_EVENT_LINK_VENUE_LAYOUT_DESC="Valgfritt tving oppsettet for lokasjonsblokk når et arrangement åpnes fra denne modulen."
MOD_JEM_EVENT_LINK_LAYOUT_DETAILS="Detaljer"
MOD_JEM_EVENT_LINK_LAYOUT_COMPACT="Kompakt"
MOD_JEM_SHOW_MORE_INFORMATION="Vis mer informasjon"
MOD_JEM_SHOW_MORE_INFORMATION_DESC="Vis en 'Mer informasjon'-lenke eller -knapp når arrangementet har en tilknyttet artikkel."
MOD_JEM_SHOW_MORE_INFORMATION_TITLE="Vis tittel for mer informasjon"
MOD_JEM_SHOW_MORE_INFORMATION_TITLE_DESC="Vis den tilknyttede artikkeltittelen etter 'Mer informasjon'-lenketeksten."
MOD_JEM_MORE_INFORMATION_LINK="Ja (lenke)"
MOD_JEM_MORE_INFORMATION_BUTTON="Ja (knapp)"
MOD_JEM_SHOW_ICON_COUNTRY_VENUE="Vis landikon"
MOD_JEM_SHOW_ICON_COUNTRY_VENUE_DESC="Vis det lille landikonet for lokasjonen for hvert arrangement."
MOD_JEM_SHOW_FLAG_ICON="Flaggikon"
MOD_JEM_DATE="Dato"
MOD_JEM_CATEGORY_ID="Kategorier"
MOD_JEM_CATEGORY_ID_DESC="Velg kategorier for å begrense utdataene til dem. La stå tomt hvis du vil vise alle arrangementer."
MOD_JEM_VENUE_ID="Lokasjoner"
MOD_JEM_VENUE_ID_DESC="Velg lokasjoner for å begrense utdataene til dem. La stå tomt hvis du vil vise alle arrangementer."
MOD_JEM_DATE_FORMAT="Datoformat"
MOD_JEM_DATE_FORMAT_DESC="Datoformat som bruker PHP-datoformatet, for eksempel: 'j. M Y'. For mer informasjon <a href='https://www.php.net/manual/en/datetime.format.php' target='_blank'>besøk PHP-manualen</a>."
MOD_JEM_TIME_FORMAT="Tidsformat"
MOD_JEM_TIME_FORMAT_DESC="Tidsformat som bruker PHP-tidsformatet, for eksempel: 'H:i'. For mer informasjon <a href='https://www.php.net/manual/en/datetime.format.php' target='_blank'>besøk PHP-manualen</a>."
MOD_JEM_MODULE_CLASS_SUFFIX="Suffiks for modulklasse"
MOD_JEM_MODULE_CLASS_SUFFIX_DESC="Et suffiks som skal brukes på modulens CSS-klasse, dette tillater individuell modulstyling."
MOD_JEM_CACHING="Bufring"
MOD_JEM_CACHING_DESC="Velg om innholdet i denne modulen skal bufres."
MOD_JEM_NO_CACHING="Ingen bufring"
MOD_JEM_CACHE_TIME="Bufringstid"
MOD_JEM_CACHE_TIME_DESC="Tiden før modulen bufres på nytt."
MOD_JEM="JEM - Grunnmodul"
MOD_JEM_XML_DESCRIPTION="JEM Grunnmodul <br>Viser arrangementer i en modulposisjon"

; Frontend
MOD_JEM_NO_EVENTS="Ingen arrangementer funnet."
MOD_JEM_MORE_INFORMATION="Mer informasjon"
MOD_JEM_ALL_DAY="Hele dagen"

; Module intro and footer text
MOD_JEM_MODULE_TEXT_BLOCK="Modulens innledningstekst og bunntekst"
MOD_JEM_SHOW_INTROTEXT="Vis innledningstekst"
MOD_JEM_SHOW_INTROTEXT_DESC="Vis egendefinert tekst over modulens innhold."
MOD_JEM_INTROTEXT="Innledningstekst"
MOD_JEM_INTROTEXT_DESC="Tekst som vises over modulens innhold."
MOD_JEM_SHOW_FOOTERTEXT="Vis bunntekst"
MOD_JEM_SHOW_FOOTERTEXT_DESC="Vis egendefinert tekst under modulens innhold."
MOD_JEM_FOOTERTEXT="Bunntekst"
MOD_JEM_FOOTERTEXT_DESC="Tekst som vises under modulens innhold."