; @package    JEM
; @subpackage JEM Calendar Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2008 Toni Smillie www.qivva.com
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_CAL="JEM - Kalendermodul"
MOD_JEM_CAL_XML_DESCRIPTION="Viser arrangementer som en månedskalender i en modulposisjon."
MOD_JEM_CAL_SHOW_TOOLTIPS="Vis verktøytips"
MOD_JEM_CAL_SHOW_TOOLTIPS_DESC="Velg å vise verktøytips ved musepeker over kalenderdatoer."
MOD_JEM_CAL_SHOW_TOOLTIPS_TITLE="Vis tittel på verktøytips"
MOD_JEM_CAL_SHOW_TOOLTIPS_TITLE_DESC="Velg å vise tittelen på verktøytips."
MOD_JEM_CAL_TOOLTIPS_TITLE_SINGULAR="Tittel på verktøytips (entall)"
MOD_JEM_CAL_TOOLTIPS_TITLE_SINGULAR_DESC="Definer tittelen på verktøytips som skal vises hvis verktøytipset inneholder ett enkelt arrangement."
MOD_JEM_CAL_TOOLTIPS_TITLE_PLURAL="Tittel på verktøytips (flertall)"
MOD_JEM_CAL_TOOLTIPS_TITLE_PLURAL_DESC="Definer tittelen på verktøytips som skal vises hvis verktøytipset inneholder flere arrangementer."
MOD_JEM_CAL_TOOLTIPS_MAX_EVENTS="Maks. arrangementer i verktøytips"
MOD_JEM_CAL_TOOLTIPS_MAX_EVENTS_DESC="Begrenser antall arrangementer vist i verktøytipset, la stå tomt for ingen grense."
MOD_JEM_CAL_TOOLTIPS_MAX_EVENT_TITLE_LENGTH="Maks. lengde på arrangementstittel"
MOD_JEM_CAL_TOOLTIPS_MAX_EVENT_TITLE_LENGTH_DESC="Begrenser lengden på arrangementstitler vist i verktøytips, la stå tomt for ingen grense."
MOD_JEM_CAL_SHOW_TOOLTIPS_LINK="Vis lenke i verktøytips"
MOD_JEM_CAL_SHOW_TOOLTIPS_LINK_DESC="Vis arrangementets lenker i verktøytips."
MOD_JEM_CAL_EVENT_LINK_EVENT_LAYOUT="Oppsett for arrangementsblokk"
MOD_JEM_CAL_EVENT_LINK_EVENT_LAYOUT_DESC="Valgfritt tving oppsettet for arrangementsblokk når et arrangement åpnes fra denne modulen."
MOD_JEM_CAL_EVENT_LINK_VENUE_LAYOUT="Oppsett for lokasjonsblokk"
MOD_JEM_CAL_EVENT_LINK_VENUE_LAYOUT_DESC="Valgfritt tving oppsettet for lokasjonsblokk når et arrangement åpnes fra denne modulen."
MOD_JEM_CAL_EVENT_LINK_LAYOUT_DETAILS="Detaljer"
MOD_JEM_CAL_EVENT_LINK_LAYOUT_COMPACT="Kompakt"
MOD_JEM_CAL_SHOW_TOOLTIPS_TIME="Vis tid i verktøytips"
MOD_JEM_CAL_SHOW_TOOLTIPS_TIME_DESC="Vis arrangementets tider i verktøytips."
MOD_JEM_CAL_SHOW_TOOLTIPS_CATEGORY="Vis kategori i verktøytips"
MOD_JEM_CAL_SHOW_TOOLTIPS_CATEGORY_DESC="Vis arrangementets kategori(er) i verktøytips."
MOD_JEM_CAL_SHOW_TOOLTIPS_VENUE="Vis lokasjon i verktøytips"
MOD_JEM_CAL_SHOW_TOOLTIPS_VENUE_DESC="Vis arrangementets lokasjon i verktøytips."
MOD_JEM_CAL_DAYNAME_LENGTH="Lengde på dagnavn"
MOD_JEM_CAL_DAYNAME_LENGTH_DESC="Velg om du vil vise fullt dagnavn eller en kort versjon."
MOD_JEM_CAL_DAYNAME_DONT_DISPLAY="Ikke vis"
MOD_JEM_CAL_DAYNAME_ONE_LETTER="Ett tegn"
MOD_JEM_CAL_DAYNAME_TWO_LETTERS="To tegn"
MOD_JEM_CAL_DAYNAME_THREE_LETTERS="Tre tegn"
MOD_JEM_CAL_DAYNAME_FULL="Fullt navn"
MOD_JEM_CAL_FIRST_DAY_OF_WEEK="Start uken på"
MOD_JEM_CAL_FIRST_DAY_OF_WEEK_DESC="Angi den første dagen i uken."
MOD_JEM_CAL_YEAR_LENGTH="Årslengde"
MOD_JEM_CAL_YEAR_LENGTH_DESC="Velg å vise 2 eller 4 sifre."
MOD_JEM_CAL_TWO_DIGITS="To sifre"
MOD_JEM_CAL_FOUR_DIGITS="Fire sifre"
MOD_JEM_CAL_SHORT_MONTHNAME="Korte månedsnavn"
MOD_JEM_CAL_SHORT_MONTHNAME_DESC="Velg om du ønsker å vise forkortede eller fullstendige månedsnavn."
MOD_JEM_CAL_MONTH_OFFSET="Månedsforskyvning"
MOD_JEM_CAL_MONTH_OFFSET_DESC="Innledende forskyvning. I stedet for gjeldende måned (forskyvning 0) vil f.eks. neste måned (forskyvning 1) eller forrige måned (forskyvning -1) vises."
MOD_JEM_CAL_TIME_OFFSET="Tidsforskyvning (timer)"
MOD_JEM_CAL_TIME_OFFSET_DESC="Bruk dette KUN hvis du trenger å forskyve tiden fra serverinnstillingene."
MOD_JEM_CAL_REMEMBER="Husk"
MOD_JEM_CAL_REMEMBER_DESC="Husk hvilken måned/år som er valgt ved sidebytte, ingen tilbakehopping til gjeldende måned."
MOD_JEM_CAL_USE_AJAX="Bruk AJAX"
MOD_JEM_CAL_USE_AJAX_DESC="Hvis satt til Ja vil månedsnavigering kun be om modulinnhold i stedet for fullstendig sideoppdatering. Det vil også falle tilbake til fullstendig sideoppdatering hvis Javascript er deaktivert i brukerens nettleser."
MOD_JEM_CAL_SHOW_CURRENT_EVENTS="Vis nåværende arrangementer"
MOD_JEM_CAL_SHOW_CURRENT_EVENTS_DESC="Vis nåværende arrangementer. Ikke sett både dette og Vis arkiverte arrangementer til Nei, ellers vil INGEN arrangementer vises."
MOD_JEM_CAL_SHOW_ARCHIVED_EVENTS="Vis arkiverte arrangementer"
MOD_JEM_CAL_SHOW_ARCHIVED_EVENTS_DESC="Vis arkiverte arrangementer. Ikke sett både dette og Vis nåværende arrangementer til Nei, ellers vil INGEN arrangementer vises."
MOD_JEM_CAL_LIMIT_TO_CATEGORY_IDS="Begrens til kategorier"
MOD_JEM_CAL_LIMIT_TO_CATEGORY_IDS_DESC="Vis en kalender kun for den valgte kategorien/kategoriene. La stå tomt for ingen begrensning."
MOD_JEM_CAL_LIMIT_TO_VENUE_IDS="Begrens til lokasjoner"
MOD_JEM_CAL_LIMIT_TO_VENUE_IDS_DESC="Vis en kalender kun for den valgte lokasjonen/lokasjonene. La stå tomt for ingen begrensning."
MOD_JEM_CAL_STRAIGHT_TO_DETAILS="Gå direkte til detaljer"
MOD_JEM_CAL_STRAIGHT_TO_DETAILS_DESC="Gå direkte til detaljsiden når det bare er ett arrangement å velge mellom."
MOD_JEM_CAL_DEFAULT_CSS="Bruk standard CSS"
MOD_JEM_CAL_DEFAULT_CSS_DESC="Bruk standard stilark modules/mod_jem_cal/mod_jemcal.css"
MOD_JEM_CAL_USER_CSS="Bruk alternativ CSS"
MOD_JEM_CAL_USER_CSS_DESC="Bruk et alternativt stilark, f.eks. modules/mod_jem_cal/mystylesheet.css. Vennligst fyll inn full bane til din CSS-fil, som i eksemplet!"
MOD_JEM_CAL_MODULE_CLASS_SUFFIX="Suffiks for modulklasse"
MOD_JEM_CAL_MODULE_CLASS_SUFFIX_DESC="Et suffiks som skal brukes på modulens CSS-klasse (table.moduletable), dette tillater individuell modulstyling."
MOD_JEM_CAL_DEFAULT_ITEM_ID="Standard menyelement-ID"
MOD_JEM_CAL_DEFAULT_ITEM_ID_DESC="Overstyr ItemID som brukes når kalenderlenken går direkte til detaljer til et menyelement du velger."
MOD_JEM_CAL_EVENT="Arrangement"
MOD_JEM_CAL_EVENTS="Arrangementer"
MOD_JEM_CAL_CACHING="Bufring"
MOD_JEM_CAL_CACHING_DESC="Velg om innholdet i denne modulen skal bufres."
MOD_JEM_CAL_CACHE_TIME="Bufringstid"
MOD_JEM_CAL_CACHE_TIME_DESC="Tiden før modulen bufres på nytt."

; Module intro and footer text
MOD_JEM_CAL_MODULE_TEXT_BLOCK="Modulens innledningstekst og bunntekst"
MOD_JEM_CAL_SHOW_INTROTEXT="Vis innledningstekst"
MOD_JEM_CAL_SHOW_INTROTEXT_DESC="Vis egendefinert tekst over modulens innhold."
MOD_JEM_CAL_INTROTEXT="Innledningstekst"
MOD_JEM_CAL_INTROTEXT_DESC="Tekst som vises over modulens innhold."
MOD_JEM_CAL_SHOW_FOOTERTEXT="Vis bunntekst"
MOD_JEM_CAL_SHOW_FOOTERTEXT_DESC="Vis egendefinert tekst under modulens innhold."
MOD_JEM_CAL_FOOTERTEXT="Bunntekst"
MOD_JEM_CAL_FOOTERTEXT_DESC="Tekst som vises under modulens innhold."

