; @package    JEM
; @subpackage JEM Tag Plugin for AcyMailing 5.x
; @copyright  (C) 2013-2017 joomlaeventmanager.net
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note : All ini files need to be saved as UTF-8 - No BOM

PLG_TAGJEM_HELP="Hjelp"
PLG_TAGJEM_HELP_DESC="Klikk på hjelpeknappen for å få hjelp."
PLG_TAGJEM_HIDE_PAST_EVENTS="Skjul tidligere arrangementer"
PLG_TAGJEM_HIDE_PAST_EVENTS_DESC="Vil du skjule tidligere arrangementer?"
PLG_TAGJEM_FEATURED_EVENTS="Begrens til utvalgte arrangementer"
PLG_TAGJEM_FEATURED_EVENTS_DESC="Vil du kun vise utvalgte arrangementer? -- Standardverdi"
PLG_TAGJEM_SHOW_IMAGES="Vis bilder"
PLG_TAGJEM_SHOW_IMAGES_DESC="Vis arrangementsbilder? -- Standardverdi"
PLG_TAGJEM_IMAGE_WIDTH="Maks. bildebredde"
PLG_TAGJEM_IMAGE_WIDTH_DESC="Maksimal bredde på arrangementsbilder i tilfelle Vis bilder tilpasset er valgt ovenfor -- Standardverdi"
PLG_TAGJEM_IMAGE_HEIGHT="Maks. bildehøyde"
PLG_TAGJEM_IMAGE_HEIGHT_DESC="Maksimal høyde på arrangementsbilder i tilfelle Vis bilder tilpasset er valgt ovenfor -- Standardverdi"
PLG_TAGJEM_DEFAULT_ITEM_ID="Standard menyelement-ID"
PLG_TAGJEM_DEFAULT_ITEM_ID_DESC="ID for et menyelement som refererer til en JEM-visning (liste)"
PLG_TAGJEM_OPTION_NO_SHOW_ALL="Nei, vis alle"
PLG_TAGJEM_OPTION_YES_FETURED_ONLY="Ja, kun utvalgte"
PLG_TAGJEM_OPTION_RESIZED="Tilpasset"
PLG_TAGJEM_TITLE="Tittel"
PLG_TAGJEM_DESCRIPTION="Beskrivelse"
PLG_TAGJEM_DATE="Dato"
PLG_TAGJEM_ID="Id"
PLG_TAGJEM_RESIZE="Tilpass størrelse"
PLG_TAGJEM_TEMPLATE="Mal"
PLG_TAGJEM_CONTACT="Kontakt"
PLG_TAGJEM_PHONE="Telefon"
PLG_TAGJEM_CELLPHONE="Mobil / SMS"
PLG_TAGJEM_VENUE="Sted"