; @package    JEM
; @subpackage JEM Latest Events Wide Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2005-2009 Christoph Lukes
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_WIDE_EVENTS_IN_MODULE="Events in module"
MOD_JEM_WIDE_EVENTS_IN_MODULE_DESC="Number of events shown in module."
MOD_JEM_WIDE_UPCOMING_ARCHIVED_OR_CURRENT="Events Display-Type"
MOD_JEM_WIDE_UPCOMING_ARCHIVED_OR_CURRENT_DESC="Select if you want to display upcoming, unfinished, archived or today's Events."
MOD_JEM_WIDE_UPCOMING_EVENTS="Upcoming"
MOD_JEM_WIDE_UNFINISHED_EVENTS="Unfinished"
MOD_JEM_WIDE_ARCHIVED_EVENTS="Archived"
MOD_JEM_WIDE_CURRENT_EVENTS="Today"
MOD_JEM_WIDE_SHOW_NO_EVENTS="Show 'No events'"
MOD_JEM_WIDE_SHOW_NO_EVENTS_DESC="Text anzeigen, wenn kein solcher Event gefunden wurde. Sonst wird das Modul nicht angezeigt."
MOD_JEM_HIGHLIGHT_FEATURED="Hervogehobene Events markieren"
MOD_JEM_HIGHLIGHT_FEATURED_DESC="Zeige einen besonderen Stil für die hervorgehobenen Events an, standardmäßig fett."
MOD_JEM_WIDE_OFFSET_HOURS="Time offset (in hours)"
MOD_JEM_WIDE_OFFSET_HOURS_DESC="Verschiebt die Zeit in die Zukunft (mit positiven Werten) oder in die Vergangenheit (mit negativen Werten). Wird nur für nicht archivierte Events verwendet. Bei heutigen Veranstaltungen wird gerundet auf ganze Tage.<br>Beispiele: Zur Anzeige von Veranstaltungen, die wenigstens vor zwei Stunden beendet wurden, Typ auf 'unbeendet' und Zeitverschiebung auf '-2' setzen. Für Veranstaltungen, die erst in einer Woche oder später beginnen, Typ auf kommend und Offset auf 168 (7 * 24) setzen. Zur Anzeige von morgigen Veranstaltungen, Typ auf 'Heute' und Zeitverschiebung auf '24' setzen."
MOD_JEM_WIDE_VENUE="Venue"
MOD_JEM_WIDE_MAX_TITLE_LENGTH="Max. Title length"
MOD_JEM_WIDE_MAX_TITLE_LENGTH_DESC="Max. length of the title."
MOD_JEM_WIDE_LINK_TO_EVENT="Link to Event on Title"
MOD_JEM_WIDE_LINK_TO_EVENT_DESC="Link to the event page on Title."
MOD_JEM_WIDE_EVENT_LINK_EVENT_LAYOUT="Layout des Event-Blocks"
MOD_JEM_WIDE_EVENT_LINK_EVENT_LAYOUT_DESC="Erzwingen Sie optional das Layout der Ereignisblöcke, wenn ein Ereignis aus diesem Modul geöffnet wird."
MOD_JEM_WIDE_EVENT_LINK_VENUE_LAYOUT="Layout des Lokalitäts-Blocks"
MOD_JEM_WIDE_EVENT_LINK_VENUE_LAYOUT_DESC="Erzwingen Sie optional das Layout der Lokalitäts-Blöcke, wenn Sie einen Event aus diesem Modul heraus öffnen."
MOD_JEM_WIDE_EVENT_LINK_LAYOUT_DETAILS="Details"
MOD_JEM_WIDE_EVENT_LINK_LAYOUT_COMPACT="Kompakt"
MOD_JEM_WIDE_SHOW_MORE_INFORMATION="Mehr Infos"
MOD_JEM_WIDE_SHOW_MORE_INFORMATION_DESC="Anzeige eines 'Mehir Info' Links oder Taste, wenn der Event einen assoziierten Betrag hat."
MOD_JEM_WIDE_SHOW_MORE_INFORMATION_TITLE="Mehr Infos anzeigen"
MOD_JEM_WIDE_SHOW_MORE_INFORMATION_TITLE_DESC="Anzeige des Titels des assoziierten Textes nach dem 'Mehr Infos' Link.\n"
MOD_JEM_WIDE_MORE_INFORMATION_LINK="Ja (Link)"
MOD_JEM_WIDE_MORE_INFORMATION_BUTTON="Ja (Taste)"
MOD_JEM_WIDE_LINK_TO_CATEGORY="Link to Category"
MOD_JEM_WIDE_LINK_TO_CATEGORY_DESC="Link to the Category."
MOD_JEM_WIDE_SHOW_CATEGORY="Anzeige der Kategorie"
MOD_JEM_WIDE_SHOW_CATEGORY_DESC="Soll die Event Kategorie angezeigt werden"
MOD_JEM_WIDE_SHOW_VENUE="Anzeige der Lokalitäts-Bezeichnung"
MOD_JEM_WIDE_SHOW_VENUE_DESC="Soll die Eventlokalität angezeigt werden?"
MOD_JEM_WIDE_LINK_TO_VENUE="Link zur Lokalität"
MOD_JEM_WIDE_LINK_TO_VENUE_DESC="Link zur Lokalität"
MOD_JEM_WIDE_USE_MODAL="Modal window"
MOD_JEM_WIDE_USE_MODAL_DESC="The modal window shows the image in original size after a click with a nice effect within the current screen"
MOD_JEM_WIDE_DATE="Date"
MOD_JEM_WIDE_CATEGORY_ID="Categories"
MOD_JEM_WIDE_CATEGORY_ID_DESC="Kategorien wählen, wenn nur deren Events angezeigt werden sollen. Leerlassen, wenn alle Events angezeigt werden sollen."
MOD_JEM_WIDE_VENUE_ID="Lokalitäten"
MOD_JEM_WIDE_VENUE_ID_DESC="Lokalitäten auswählen, deren Events nur angezeigt werden sollen. Leerlassen, um alle Events anzuzeigen."
MOD_JEM_WIDE_SHOW_DATE="Show date"
MOD_JEM_WIDE_SHOW_DAY_DIFFERENCE="Show day difference"
MOD_JEM_WIDE_SHOW_DATE_OR_DAY_DIFFERENCE="Date Display-Type"
MOD_JEM_WIDE_SHOW_DATE_OR_DAY_DIFFERENCE_DESC="Select to show the formatted date or the difference in days from current day to the Event date. Note: The time will be hidden when the day difference is selected."
MOD_JEM_WIDE_DATE_FORMAT="Date format"
MOD_JEM_WIDE_DATE_FORMAT_DESC="Datumsformat mit dem PHP-Datumsformat, z.B. 'Y-m-d' für 2017-06-15. Für weitere Infos bitte <a href='https://www.php.net/manual/en/datetime.format.php' target='_blank'>das PHP-Handbuch benutzen</a>."
MOD_JEM_WIDE_TIME_FORMAT="Time format"
MOD_JEM_WIDE_TIME_FORMAT_DESC="Zeit-Format verwendet das PHP Zeit-Format, z.B. 'H:i'. Für weitere Infos bitte <a href='https://www.php.net/manual/en/datetime.format.php' target='_blank'>das PHP-Handbuch benutzen</a>."
MOD_JEM_WIDE_MODULE_CLASS_SUFFIX="Modulklassen-Suffix"
MOD_JEM_WIDE_MODULE_CLASS_SUFFIX_DESC="Ein Suffix, das an die css-Klasse des Moduls angehängt wird und die individuelle Gestaltung des Moduls ermöglicht."
MOD_JEM_WIDE_CACHING="Caching"
MOD_JEM_WIDE_CACHING_DESC="Select whether to cache the content of this module."
MOD_JEM_WIDE_CACHE_TIME="Cache Time"
MOD_JEM_WIDE_CACHE_TIME_DESC="Die Zeit, bis das Modul erneut zwischengespeichert wird."

MOD_JEM_WIDE="JEM - Wide Modul"
MOD_JEM_WIDE_XML_DESCRIPTION="JEM Wide Module <br>Displays events in a module position at a wide orientation"
MOD_JEM_WIDE_MORE_INFORMATION="Mehr Infos"

; Frontend
MOD_JEM_WIDE_TODAY="Today"
MOD_JEM_WIDE_TOMORROW="Tomorrow"
MOD_JEM_WIDE_YESTERDAY="Yesterday"
MOD_JEM_WIDE_DAYS_AGO="%s days ago"
MOD_JEM_WIDE_DAYS_AHEAD="%s days ahead"
MOD_JEM_WIDE_ENDED_DAYS_AGO="Ended %s days ago"
MOD_JEM_WIDE_STARTED_DAYS_AGO="Started %s days ago"
MOD_JEM_WIDE_FROM="From %s"
MOD_JEM_WIDE_UNTIL="Until %s"
MOD_JEM_WIDE_FROM_UNTIL="From %s Until %s"
MOD_JEM_WIDE_ON_DATE="On %s"
MOD_JEM_WIDE_NO_EVENTS="No events found."
; Module intro and footer text
MOD_JEM_WIDE_MODULE_TEXT_BLOCK="Intro- und Fußtext des Moduls"
MOD_JEM_WIDE_SHOW_INTROTEXT="Kopftext anzeigen"
MOD_JEM_WIDE_SHOW_INTROTEXT_DESC="Anzeige von benutzerdef. Text über Modulinhalt"
MOD_JEM_WIDE_INTROTEXT="Kopftext"
MOD_JEM_WIDE_INTROTEXT_DESC="Über Modulinhalt angezeigter Text"
MOD_JEM_WIDE_SHOW_FOOTERTEXT="Fußzeile anzeigen"
MOD_JEM_WIDE_SHOW_FOOTERTEXT_DESC="Anzeige von benutzerdef. Text nach Modulinhalt"
MOD_JEM_WIDE_FOOTERTEXT="Fußtext"
MOD_JEM_WIDE_FOOTERTEXT_DESC="Nach Modulinhalt angezeigter Text"
