; @package    JEM
; @subpackage JEM Map Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_MAP="JEM - Lokalitäten Karten Modul"
MOD_JEM_MAP_XML_DESCRIPTION="Dieses Modul zeigt JEM Örtlichkeiten mit Events auf einer interaktiven Karte an, die Länge und Breite in JEM haben."
MOD_JEM_MAP_SHOW_COUNTRY_FILTER="Bundeslandfilter anzeigen"
MOD_JEM_MAP_SHOW_COUNTRY_FILTER_DESC="Zeigt eine Wahlmöglichkeit für Regionen über der Karte an."
MOD_JEM_MAP_COUNTRY_FILTER="Länderfilter"
MOD_JEM_MAP_ALL_COUNTRIES="Alle Länder"
MOD_JEM_MAP_DEFAULT_COUNTRY="Standard-Region"
MOD_JEM_MAP_DEFAULT_COUNTRY_DESC="Wähle das verwendete Land als Standard für die Karte. Leerlassen, um Lokalitäten aller Länder anzuzeigen.\n\n\n"
; Module intro and footer text
MOD_JEM_MAP_MODULE_TEXT_BLOCK="Intro- und Fußtext des Moduls"
MOD_JEM_MAP_SHOW_INTROTEXT="Kopftext anzeigen"
MOD_JEM_MAP_SHOW_INTROTEXT_DESC="Anzeige von benutzerdef. Text über Modulinhalt"
MOD_JEM_MAP_INTROTEXT="Kopftext"
MOD_JEM_MAP_INTROTEXT_DESC="Über Modulinhalt angezeigter Text"
MOD_JEM_MAP_SHOW_FOOTERTEXT="Fußzeile anzeigen"
MOD_JEM_MAP_SHOW_FOOTERTEXT_DESC="Anzeige von benutzerdef. Text nach Modulinhalt"
MOD_JEM_MAP_FOOTERTEXT="Fußtext"
MOD_JEM_MAP_FOOTERTEXT_DESC="Nach Modulinhalt angezeigter Text"
