; @package    JEM
; @subpackage JEM Teaser Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2005-2009 Christoph Lukes
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_TEASER="JEM - Teaser-Module"
MOD_JEM_TEASER_XML_DESCRIPTION="Dieses Modul zeigt Veranstaltungen als Teaser"
MOD_JEM_TEASER_EVENT_LINK_EVENT_LAYOUT="Layout des Event-Blocks"
MOD_JEM_TEASER_EVENT_LINK_EVENT_LAYOUT_DESC="Erzwingen Sie optional das Layout der Ereignisblöcke, wenn ein Ereignis aus diesem Modul geöffnet wird."
MOD_JEM_TEASER_EVENT_LINK_VENUE_LAYOUT="Layout des Lokalitäts-Blocks"
MOD_JEM_TEASER_EVENT_LINK_VENUE_LAYOUT_DESC="Erzwingen Sie optional das Layout der Lokalitäts-Blöcke, wenn Sie einen Event aus diesem Modul heraus öffnen."
MOD_JEM_TEASER_EVENT_LINK_LAYOUT_DETAILS="Details"
MOD_JEM_TEASER_EVENT_LINK_LAYOUT_COMPACT="Kompakt"
; Module intro and footer text
MOD_JEM_TEASER_MODULE_TEXT_BLOCK="Intro- und Fußtext des Moduls"
MOD_JEM_TEASER_SHOW_INTROTEXT="Kopftext anzeigen"
MOD_JEM_TEASER_SHOW_INTROTEXT_DESC="Anzeige von benutzerdef. Text über Modulinhalt"
MOD_JEM_TEASER_INTROTEXT="Kopftext"
MOD_JEM_TEASER_INTROTEXT_DESC="Über Modulinhalt angezeigter Text"
MOD_JEM_TEASER_SHOW_FOOTERTEXT="Fußzeile anzeigen"
MOD_JEM_TEASER_SHOW_FOOTERTEXT_DESC="Anzeige von benutzerdef. Text nach Modulinhalt"
MOD_JEM_TEASER_FOOTERTEXT="Fußtext"
MOD_JEM_TEASER_FOOTERTEXT_DESC="Nach Modulinhalt angezeigter Text"
