; JEM Types Module - sys.ini
MOD_JEM_TYPES="JEM - Typen"
MOD_JEM_TYPES_XML_DESCRIPTION="Zeigt eine Liste der Event-Typen mit der Anzahl der anstehenden Events oder den wichtigsten anstehenden Events pro Typ."
MOD_JEM_TYPES_EVENT_LINK_EVENT_LAYOUT="Event Block Layout"
MOD_JEM_TYPES_EVENT_LINK_EVENT_LAYOUT_DESC="Erzwinge optional das Layout des Ereignisblocks, wenn ein Ereignis aus diesem Modul geöffnet wird."
MOD_JEM_TYPES_EVENT_LINK_VENUE_LAYOUT="Ort Blocklayout"
MOD_JEM_TYPES_EVENT_LINK_VENUE_LAYOUT_DESC="Erzwingen Sie optional das Layout des Veranstaltungsblocks beim Öffnen eines Ereignisses aus diesem Modul."
MOD_JEM_TYPES_EVENT_LINK_LAYOUT_DETAILS="Details"
MOD_JEM_TYPES_EVENT_LINK_LAYOUT_COMPACT="Kompakt"
; Module intro and footer text
MOD_JEM_TYPES_MODULE_TEXT_BLOCK="Moduleinführung und Fußzeile"
MOD_JEM_TYPES_SHOW_INTROTEXT="Einleitungstext anzeigen"
MOD_JEM_TYPES_SHOW_INTROTEXT_DESC="Benutzerdefinierten Text über dem Modulinhalt anzeigen."
MOD_JEM_TYPES_INTROTEXT="Einführungstext"
MOD_JEM_TYPES_INTROTEXT_DESC="Text, der oberhalb des Modulinhalts angezeigt wird."
MOD_JEM_TYPES_SHOW_FOOTERTEXT="Fußzeilentext anzeigen"
MOD_JEM_TYPES_SHOW_FOOTERTEXT_DESC="Benutzerdefinierten Text unter dem Modulinhalt anzeigen."
MOD_JEM_TYPES_FOOTERTEXT="Fußzeilentext"
MOD_JEM_TYPES_FOOTERTEXT_DESC="Text, der unter dem Modulinhalt angezeigt wird."

