; @package    JEM
; @subpackage JEM Jubilee Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2005-2009 Christoph Lukes
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_JUBILEE_EVENTS_IN_MODULE="Anzahl Veranstaltungen"
MOD_JEM_JUBILEE_EVENTS_IN_MODULE_DESC="Die maximale Anzahl an Veranstaltungen die im Modul dargestellt werden sollen"
MOD_JEM_JUBILEE_SHOW_NO_EVENTS="'Keine Events' anzeigen, wenn keine solchen vorhanden"
MOD_JEM_JUBILEE_SHOW_NO_EVENTS_DESC="Text anzeigen, wenn kein solcher Event gefunden wurde. Sonst wird das Modul nicht angezeigt."
MOD_JEM_JUBILEE_PUBLISHING_STATE="Veröffentlichungsstatus"
MOD_JEM_JUBILEE_PUBLISHING_STATE_DESC="Wählen, ob archivierte oder veröffentlichte Events oder beide angezeigt werden sollen. Lässt du archivierte JEM Events anzeigen, kannst du hier entscheiden, ob 'Heutige Events' (publizierte) Events oder 'Jubiläums-Anlässe' (archiviert) angezeigt werden. "
MOD_JEM_JUBILEE_PUBLISHED_EVENTS="Freigegebene Events"
MOD_JEM_JUBILEE_ARCHIVED_EVENTS="Archivierte Events"
MOD_JEM_JUBILEE_BOTH_EVENTS="beide"
MOD_JEM_JUBILEE_OFFSET_DAYS="Verschiebung in  Tagen"
MOD_JEM_JUBILEE_OFFSET_DAYS_DESC="Verschiebt Daten in die Zukunft (positive Werte) oder in Vergangenheit (negative Werte)."
MOD_JEM_JUBILEE_DATE_MATCH_MODE="Datumsübereinstimmungs-Modus"
MOD_JEM_JUBILEE_DATE_MATCH_MODE_DESC="Zeigen Sie mehrtägige Ereignisse an, wenn Tag und Monat mit dem Startdatum, dem Enddatum, einem der beiden oder einem beliebigen Datum zwischen Start- und Enddatum übereinstimmen. Bei eintägigen Ereignissen gibt es keinen Unterschied.\n "
MOD_JEM_JUBILEE_SHOW_PAST_YEAR_EVENTS="Vergangene Jahre einbeziehen"
MOD_JEM_JUBILEE_SHOW_PAST_YEAR_EVENTS_DESC="Wenn Ja, werden Veranstaltungen vergangener Jahre mit einbezogen."
MOD_JEM_JUBILEE_DATE_MATCH_FROM_START_TO_END="Jederzeit zwischen Start- und Enddatum"
MOD_JEM_JUBILEE_DATE_MATCH_ON_START="Exakt beim Startdatum"
MOD_JEM_JUBILEE_DATE_MATCH_ON_END="Exakt beim Enddatum"
MOD_JEM_JUBILEE_DATE_MATCH_ON_START_OR_END="Exakt beim Start- oder Enddatum"
MOD_JEM_JUBILEE_VENUE="Lokalität"
MOD_JEM_JUBILEE_MAX_TITLE_LENGTH="Max. Titellänge"
MOD_JEM_JUBILEE_MAX_TITLE_LENGTH_DESC="Maximale Länge des Titels, die angezeigt wird."
MOD_JEM_JUBILEE_LINK_TO_DETAILS="Link zum Event"
MOD_JEM_JUBILEE_LINK_TO_DETAILS_DESC="Link zur Veranstaltungsseite auf Titel"
MOD_JEM_JUBILEE_EVENT_LINK_EVENT_LAYOUT="Layout des Event-Blocks"
MOD_JEM_JUBILEE_EVENT_LINK_EVENT_LAYOUT_DESC="Erzwingen Sie optional das Layout der Ereignisblöcke, wenn ein Ereignis aus diesem Modul geöffnet wird."
MOD_JEM_JUBILEE_EVENT_LINK_VENUE_LAYOUT="Layout des Lokalitäts-Blocks"
MOD_JEM_JUBILEE_EVENT_LINK_VENUE_LAYOUT_DESC="Erzwingen Sie optional das Layout der Lokalitäts-Blöcke, wenn Sie einen Event aus diesem Modul heraus öffnen."
MOD_JEM_JUBILEE_EVENT_LINK_LAYOUT_DETAILS="Details"
MOD_JEM_JUBILEE_EVENT_LINK_LAYOUT_COMPACT="Kompakt"
MOD_JEM_JUBILEE_SHOWDESC="Eventbeschreibung anzeigen"
MOD_JEM_JUBILEE_SHOWDESC_DESC="Anzeige der Event-Beschreibung"
MOD_JEM_JUBILEE_SHOWFLYER="Bild anzeigen"
MOD_JEM_JUBILEE_SHOWFLYER_DESC="Bild der Veranstaltung anzeigen oder verbergen."
MOD_JEM_JUBILEE_SHOWVENUE="Lokalität anzeigen"
MOD_JEM_JUBILEE_SHOWVENUE_DESC="Lokalität anzeigen oder verbergen"
MOD_JEM_JUBILEE_SHOWCATEGORY="Kategorie anzeigen"
MOD_JEM_JUBILEE_SHOWCATEGORY_DESC="Kategorie anzeigen oder verbergen"
MOD_JEM_JUBILEE_LINK_TO_CATEGORY="Link zur Kategorie"
MOD_JEM_JUBILEE_LINK_TO_CATEGORY_DESC="Link zur Kategorie. Nur, wenn Kategorie anzeigen oben gewählt wurde!"
MOD_JEM_JUBILEE_LINK_TO_VENUE="Link zur Lokalität"
MOD_JEM_JUBILEE_LINK_TO_VENUE_DESC="Link zu Lokalität. Nur, wenn Lokalität anzeigen oben gewählt wurde!"
MOD_JEM_JUBILEE_FLYER_LINKS_TO="Bild ist verlinkt zu …"
MOD_JEM_JUBILEE_FLYER_LINKS_TO_DESC="Ein Klick auf den Flyer des Bildes zeigt den Flyer entweder in Originalgröße auf voller Seite, den Flyer in einem Modalen Fenster oder öffnet die Detailansicht der Veranstaltung. Dies setzt voraus, dass Anzeige des Flyers aktiviert ist."
MOD_JEM_JUBILEE_FLYER_LINK_IMAGE_PAGE="Flyer auf voller Seite"
MOD_JEM_JUBILEE_FLYER_LINK_IMAGE_MODAL="Bild in modalem Fenster"
MOD_JEM_JUBILEE_FLYER_LINK_EVENT_DETAILS="Detailansicht der Veranstaltung"
MOD_JEM_JUBILEE_DATE="Datum"
MOD_JEM_JUBILEE_CATEGORY_ID="Kategorien"
MOD_JEM_JUBILEE_CATEGORY_ID_DESC="Kategorien wählen, deren Events nur angezeigt werden sollen. Leerlassen, wenn alle Events angezeigt werden sollen."
MOD_JEM_JUBILEE_VENUE_ID="Lokalitäten"
MOD_JEM_JUBILEE_VENUE_ID_DESC="Lokalitäten auswählen, deren Events nur angezeigt werden sollen. Leerlassen, um alle Events anzuzeigen"
MOD_JEM_JUBILEE_STATE="Bundesland"
MOD_JEM_JUBILEE_STATE_DESC="Mit Komma getrennte Regionen/Bundesländer eingeben, um auf die gewählten zu begrenzen. Leerlassen für alle."
MOD_JEM_JUBILEE_STATE_MODE="Bundesland Übereinstimmungs Modus"
MOD_JEM_JUBILEE_STATE_MODE_DESC="Wählen, ob beim Bundesland die oben eingegebenen Zeichen vollständig übereinstimmen sollen  oder nur enthalten sein sollen."
MOD_JEM_JUBILEE_STATE_MODE_EXACTMATCH="Vollständige Übereinstimmung"
MOD_JEM_JUBILEE_STATE_MODE_CONTAINS="Enthält"
MOD_JEM_JUBILEE_SHOW_DATE_OR_YEAR_DIFFERENCE="Art der Datumsanzeige"
MOD_JEM_JUBILEE_SHOW_DATE_OR_YEAR_DIFFERENCE_DESC="Select to hide date or show the formatted date or the difference in years from current day to the Event date.\nWählen, ob formatiertes Datum oder die Differenz in Jahren angezeigt werden soll."
MOD_JEM_JUBILEE_HIDE_DATE="Datum verbergen"
MOD_JEM_JUBILEE_SHOW_DATE="Datum anzeigen"
MOD_JEM_JUBILEE_SHOW_YEAR_DIFFERENCE="Differenz von Jahren anzeigen"
MOD_JEM_JUBILEE_DATE_FORMAT="Datumsformat"
MOD_JEM_JUBILEE_DATE_FORMAT_DESC="Datumsformat mit dem PHP-Datumsformat, z.B. 'Y-m-d' für 2017-06-15. Für weitere Infos bitte <a href='https://www.php.net/manual/en/datetime.format.php' target='_blank'>das PHP-Handbuch benutzen</a>."
MOD_JEM_JUBILEE_SHOWTIME="Zeit anzeigen"
MOD_JEM_JUBILEE_SHOWTIME_DESC="Zeit anzeigen oder verstecken"
MOD_JEM_JUBILEE_TIME_FORMAT="Zeit-Format"
MOD_JEM_JUBILEE_TIME_FORMAT_DESC="Zeit-Format verwendet das PHP Zeit-Format, z.B. 'H:i'. Für weitere Infos bitte <a href='https://www.php.net/manual/de/datetime.format.php' target='_blank'>das PHP-Handbuch benutzen</a>."
MOD_JEM_JUBILEE_MODULE_CLASS_SUFFIX="Modulklassen-Suffix"
MOD_JEM_JUBILEE_MODULE_CLASS_SUFFIX_DESC="Ein Suffix für die CSS-Klasse des Moduls, dies erlaubt individuelles Styling des Moduls"
MOD_JEM_JUBILEE_CACHING="Caching"
MOD_JEM_JUBILEE_CACHING_DESC="Wählen ob Inhalt dieses Moduls gechachet werden soll."
MOD_JEM_JUBILEE_CACHE_TIME="Cache-Zeit"
MOD_JEM_JUBILEE_CACHE_TIME_DESC="Die Zeit, bis das Modul erneut zwischengespeichert wird."
MOD_JEM_JUBILEE_ALLOW_LINEBREAK="Zeilenumbruch erlauben"
MOD_JEM_JUBILEE_ALLOW_LINEBREAK_DESC="Erlaubt Zeilenumbruch oder Ersatz durch Leerschlag"
MOD_JEM_JUBILEE_MAX_DESCRIPTION_LENGTH="maximale Länge der Beschreibung"
MOD_JEM_JUBILEE_MAX_DESCRIPTION_LENGTH_DESC="Begrenzung der Beschreibung auf diese Anzahl Zeichen."
MOD_JEM_JUBILEE_FIELD_READMORE_DESC="Wenn „Ja“, dann wird der Link „Weiterlesen …“ angezeigt, wenn die Beschreibung der Veranstaltung einen „Weiterlesen“-Absatz enthält"
MOD_JEM_JUBILEE_FIELD_READMORE_LABEL="'Weiterlesen …' anzeigen"
MOD_JEM_JUBILEE_SHOW_MORE_INFORMATION="Mehr Infos"
MOD_JEM_JUBILEE_SHOW_MORE_INFORMATION_DESC="Anzeige eines 'Mehir Info' Links oder Taste, wenn der Event einen assoziierten Betrag hat."
MOD_JEM_JUBILEE_SHOW_MORE_INFORMATION_TITLE="Mehr Infos anzeigen"
MOD_JEM_JUBILEE_SHOW_MORE_INFORMATION_TITLE_DESC="Anzeige des Titels des assoziierten Textes nach dem 'Mehr Infos' Link.\n"
MOD_JEM_JUBILEE_READMORE_LINK="Ja (Link)"
MOD_JEM_JUBILEE_READMORE_BUTTON="Ja (Taste)"
MOD_JEM_JUBILEE_MORE_INFORMATION_LINK="Ja (Link)"
MOD_JEM_JUBILEE_MORE_INFORMATION_BUTTON="Ja (Taste)"
MOD_JEM_JUBILEE_SHOWCALENDAR="Kalenderblatt anzeigen"
MOD_JEM_JUBILEE_SHOWCALENDAR_DESC="Zeigt ein Kalenderblatt mit Tag und Monat an"
MOD_JEM_JUBILEE_COLOR="Farbe des Kalenderblatts"
MOD_JEM_JUBILEE_COLOR_DESC="Farbe des Kalenderblatts. Wenn 'benutzerdefiniert', wird die unten gewählte Farbe genommen."
MOD_JEM_JUBILEE_BLUE="Blau"
MOD_JEM_JUBILEE_GREEN="Grün"
MOD_JEM_JUBILEE_ORANGE="Orange"
MOD_JEM_JUBILEE_RED="Rot"
MOD_JEM_JUBILEE_USER="benutzerdefiniert"
MOD_JEM_JUBILEE_USER_COLOR="Benutzerdef. Farbe"
MOD_JEM_JUBILEE_USER_COLOR_DESC="Ersatz-Farbe, wenn oben 'benutzerdefiniert' gewählt ist."
MOD_JEM_JUBILEE_SHUFFLE="Zufallswahl"
MOD_JEM_JUBILEE_SHUFFLE_DESC="Wenn es mehr Veranstaltungen gefunden werden, die angezeigt werden sollen, wird bei jedem Klick zufällig ausgewählt."
MOD_JEM_JUBILEE_SHUFFLE_COUNT="Auswahlbegrenzung"
MOD_JEM_JUBILEE_SHUFFLE_COUNT_DESC="Begrenzt aus der Datenbank ausgelesene Veranstaltungen, aber wird durch die Zahl der anzuzeigenden Veranstaltungen korrigiert."
MOD_JEM_JUBILEE_INTROTEXT="Intro Text"
MOD_JEM_JUBILEE_INTROTEXT_DESC="Rechts neben dem Kalenderbild angezeigter Text oberhalb des Events.  Mit bbCodes unterstützt sind [day], [month], [year]. Leerlassen für keinen Introtext."
MOD_JEM_JUBILEE_ORDER="Reihenfolge der Events"
MOD_JEM_JUBILEE_ORDER_DESC="Die Anordnung der angezeigten Events."
MOD_JEM_JUBILEE_ORDER_ASCENDING="Datum aufsteigend"
MOD_JEM_JUBILEE_ORDER_DESCENDING="Datum absteigend"
MOD_JEM_JUBILEE="JEM - Jubiläums-Module"
MOD_JEM_JUBILEE_XML_DESCRIPTION="JEM Jubiläums Module."

; Frontend
MOD_JEM_JUBILEE_TODAY="Heute"
MOD_JEM_JUBILEE_TOMORROW="Morgen"
MOD_JEM_JUBILEE_YESTERDAY="Gestern"
MOD_JEM_JUBILEE_FROM="%s"
MOD_JEM_JUBILEE_UNTIL="- %s"
MOD_JEM_JUBILEE_FROM_UNTIL="%s - %s"
MOD_JEM_JUBILEE_ON_DATE="%s"
MOD_JEM_JUBILEE_READMORE="Weiterlesen …"
MOD_JEM_JUBILEE_MORE_INFORMATION="Mehr Infos"
MOD_JEM_JUBILEE_READMORE_REGISTER="Einloggen, um weiterzulesen."
MOD_JEM_JUBILEE_NO_DESCRIPTION=""
MOD_JEM_JUBILEE_NO_EVENTS="Kein solcher Event gefunden"
MOD_JEM_JUBILEE_YEAR_AGO="vor %s Jahr"
MOD_JEM_JUBILEE_YEARS_AGO="vor %s Jahren"
MOD_JEM_JUBILEE_NEARLY_YEAR_AGO="Vor fast %s Jahr"
MOD_JEM_JUBILEE_NEARLY_YEARS_AGO="Vor fast %s Jahren"
MOD_JEM_JUBILEE_OVER_YEAR_AGO="vor mehr als %s Jahr"
MOD_JEM_JUBILEE_OVER_YEARS_AGO="vor mehr als %s Jahren"
MOD_JEM_JUBILEE_MONTHS_AGO="vor %s Monaten"
MOD_JEM_JUBILEE_DAYS_AGO=" vor %s Tagen"
MOD_JEM_JUBILEE_YEAR_AHEAD="in %s Jahr"
MOD_JEM_JUBILEE_YEARS_AHEAD="in %s Jahren"
MOD_JEM_JUBILEE_NEARLY_YEAR_AHEAD="in fast %s Jahr"
MOD_JEM_JUBILEE_NEARLY_YEARS_AHEAD="in fast %s Jahren"
MOD_JEM_JUBILEE_OVER_YEAR_AHEAD="In mehr als %s Jahr"
MOD_JEM_JUBILEE_OVER_YEARS_AHEAD="in mehr als  %s Jahren"
MOD_JEM_JUBILEE_MONTHS_AHEAD="in %s Monaten"
MOD_JEM_JUBILEE_DAYS_AHEAD="in %s Tagen"
MOD_JEM_JUBILEE_DAYS_LEFT="noch %s Tage"
MOD_JEM_JUBILEE_ENDED_YEAR_AGO="endete vor %s Jahr"
MOD_JEM_JUBILEE_ENDED_YEARS_AGO="endete vor %s Jahren"
MOD_JEM_JUBILEE_ENDED_NEARLY_YEAR_AGO="endete vor fast %s Jahr"
MOD_JEM_JUBILEE_ENDED_NEARLY_YEARS_AGO="endete vor fast %s Jahren"
MOD_JEM_JUBILEE_ENDED_OVER_YEAR_AGO="endete vor mehr als %s Jahr"
MOD_JEM_JUBILEE_ENDED_OVER_YEARS_AGO="endete vor mehr als %s Jahren"
MOD_JEM_JUBILEE_ENDED_DAY_AGO="Endete vor %s Tag"
MOD_JEM_JUBILEE_ENDED_DAYS_AGO="Endete vor %s Tagen"
MOD_JEM_JUBILEE_STARTED_YEAR_AGO="begann vor %s Jahr"
MOD_JEM_JUBILEE_STARTED_YEARS_AGO="begann vor %s Jahren"
MOD_JEM_JUBILEE_STARTED_NEARLY_YEAR_AGO="begann vor fast %s Jahr"
MOD_JEM_JUBILEE_STARTED_NEARLY_YEARS_AGO="begann vor fast %s Jahren"
MOD_JEM_JUBILEE_STARTED_OVER_YEAR_AGO="begann vor mehr als %s Jahr"
MOD_JEM_JUBILEE_STARTED_OVER_YEARS_AGO="begann vor mehr als %s Jahren"
MOD_JEM_JUBILEE_STARTED_DAYS_AGO="begann vor %s Tagen"
; Module intro and footer text
MOD_JEM_JUBILEE_MODULE_TEXT_BLOCK="Intro- und Fußtext des Moduls"
MOD_JEM_JUBILEE_SHOW_INTROTEXT="Kopftext anzeigen"
MOD_JEM_JUBILEE_SHOW_INTROTEXT_DESC="Anzeige von benutzerdef. Text über Modulinhalt"
MOD_JEM_JUBILEE_SHOW_FOOTERTEXT="Fußzeile anzeigen"
MOD_JEM_JUBILEE_SHOW_FOOTERTEXT_DESC="Anzeige von benutzerdef. Text nach Modulinhalt"
MOD_JEM_JUBILEE_FOOTERTEXT="Fußtext"
MOD_JEM_JUBILEE_FOOTERTEXT_DESC="Nach Modulinhalt angezeigter Text"

