; @package    JEM
; @subpackage JEM Calendar Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2008 Toni Smillie www.qivva.com
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_CAL="JEM - Kalendermodul"
MOD_JEM_CAL_XML_DESCRIPTION="Zeigt Veranstaltungen als Monatskalender an einer Modulposition an. <br>Wenn der Browser JavaScript zulässt, wird Ajax für minimales Reload bei der Monatsnavigation verwendet."
MOD_JEM_CAL_SHOW_TOOLTIPS="Tooltips anzeigen"
MOD_JEM_CAL_SHOW_TOOLTIPS_DESC="Auswählen, um Tooltips bei Maus über Datum anzuzeigen"
MOD_JEM_CAL_SHOW_TOOLTIPS_TITLE="Tooltips-Titel anzeigen"
MOD_JEM_CAL_SHOW_TOOLTIPS_TITLE_DESC="Wählen Sie diese Option, um den Titel des Tooltips anzuzeigen."
MOD_JEM_CAL_TOOLTIPS_TITLE_SINGULAR="Tooltips-Titel (Einzahl)"
MOD_JEM_CAL_TOOLTIPS_TITLE_SINGULAR_DESC="Definieren Sie den Titel des Tooltips, um anzuzeigen, ob der Tooltip eine einzelne Veranstaltung enthält."
MOD_JEM_CAL_TOOLTIPS_TITLE_PLURAL="Tooltips-Titel (Plural)"
MOD_JEM_CAL_TOOLTIPS_TITLE_PLURAL_DESC="Definieren Sie den Titel des Tooltips, um anzuzeigen, ob der Tooltip mehrere Veranstaltungen enthält."
MOD_JEM_CAL_TOOLTIPS_MAX_EVENTS="Max. Zahl Veranstaltungen in Tooltip"
MOD_JEM_CAL_TOOLTIPS_MAX_EVENTS_DESC="Begrenzt die Anzahl der im Tooltip angezeigten Veranstaltungen, bleibt leer für keine Begrenzung."
MOD_JEM_CAL_TOOLTIPS_MAX_EVENT_TITLE_LENGTH="Max. Veranstaltungstitel-Länge"
MOD_JEM_CAL_TOOLTIPS_MAX_EVENT_TITLE_LENGTH_DESC="Begrenzt die Länge von Veranstaltungstiteln, die in Tooltips angezeigt werden; leer lassen für keine Begrenzung."
MOD_JEM_CAL_SHOW_TOOLTIPS_LINK="Link in Tooltip anzeigen"
MOD_JEM_CAL_SHOW_TOOLTIPS_LINK_DESC="Zeige den/die Link(s) der Veranstaltung in Tooltips an."
MOD_JEM_CAL_EVENT_LINK_EVENT_LAYOUT="Layout des Event-Blocks"
MOD_JEM_CAL_EVENT_LINK_EVENT_LAYOUT_DESC="Erzwingen Sie optional das Layout der Ereignisblöcke, wenn ein Ereignis aus diesem Modul geöffnet wird."
MOD_JEM_CAL_EVENT_LINK_VENUE_LAYOUT="Layout des Lokalitäts-Blocks"
MOD_JEM_CAL_EVENT_LINK_VENUE_LAYOUT_DESC="Erzwingen Sie optional das Layout der Lokalitäts-Blöcke, wenn Sie einen Event aus diesem Modul heraus öffnen."
MOD_JEM_CAL_EVENT_LINK_LAYOUT_DETAILS="Details"
MOD_JEM_CAL_EVENT_LINK_LAYOUT_COMPACT="Kompakt"
MOD_JEM_CAL_SHOW_TOOLTIPS_TIME="Zeit in Tooltip anzeigen"
MOD_JEM_CAL_SHOW_TOOLTIPS_TIME_DESC="Zeige die Uhrzeit der Veranstaltung in Tooltips an."
MOD_JEM_CAL_SHOW_TOOLTIPS_CATEGORY="Kategorie in Tooltip anzeigen"
MOD_JEM_CAL_SHOW_TOOLTIPS_CATEGORY_DESC="Anzeige der Veranstaltungskategorie/n im Tooltip"
MOD_JEM_CAL_SHOW_TOOLTIPS_VENUE="Lokalität im Tooltip anzeigen"
MOD_JEM_CAL_SHOW_TOOLTIPS_VENUE_DESC="Anzeige der Lokalität in den Tooltips."
MOD_JEM_CAL_DAYNAME_LENGTH="Länge der Tagesnamen"
MOD_JEM_CAL_DAYNAME_LENGTH_DESC="Wähle, ob du den vollständigen Tagesnamen oder eine Kurzversion anzeigen möchten."
MOD_JEM_CAL_DAYNAME_DONT_DISPLAY="Nicht anzeigen"
MOD_JEM_CAL_DAYNAME_ONE_LETTER="Einzelner Buchstabe"
MOD_JEM_CAL_DAYNAME_TWO_LETTERS="Zwei Buchstaben"
MOD_JEM_CAL_DAYNAME_THREE_LETTERS="Drei Buchstaben"
MOD_JEM_CAL_DAYNAME_FULL="Vollname"
MOD_JEM_CAL_FIRST_DAY_OF_WEEK="Wochenbeginn am"
MOD_JEM_CAL_FIRST_DAY_OF_WEEK_DESC="Gib den ersten Tag der Woche an."
MOD_JEM_CAL_YEAR_LENGTH="Länge der Jahreszahl"
MOD_JEM_CAL_YEAR_LENGTH_DESC="Wählen, um 2 oder 4 Ziffern anzuzeigen."
MOD_JEM_CAL_TWO_DIGITS="Zweistellig"
MOD_JEM_CAL_FOUR_DIGITS="Vierstellig"
MOD_JEM_CAL_SHORT_MONTHNAME="Kurzform für Monatsnamen"
MOD_JEM_CAL_SHORT_MONTHNAME_DESC="Wähle aus, ob du abgekürzte oder vollständige Monatsnamen anzeigen möchten."
MOD_JEM_CAL_MONTH_OFFSET="Monatsabweichung"
MOD_JEM_CAL_MONTH_OFFSET_DESC="Startverschiebung. Anstelle des laufenden Monats (offset 0) wird z.B. kommender Monat (offset 1) oder vergangener Monat (offset -1) angezeigt."
MOD_JEM_CAL_TIME_OFFSET="Zeitverschiebung (Stunden)"
MOD_JEM_CAL_TIME_OFFSET_DESC="Bitte NUR anwenden, wenn die eigene Zeit gegenüber den Servereinstellungen verschoben werden muss!"
MOD_JEM_CAL_REMEMBER="Erinnern"
MOD_JEM_CAL_REMEMBER_DESC="Merken, welcher Monat/Jahr bei Seitenwechsel ausgewählt ist, kein Zurückspringen zum aktuellen Monat."
MOD_JEM_CAL_USE_AJAX="AJAX verwenden"
MOD_JEM_CAL_USE_AJAX_DESC="Aktiviert, wird durch die Monatsnavigation nur der Modulinhalt anstelle der ganzen Seite neu geladen. Wenn Javascript durch den Browser des Benutzers deaktiviert ist, wird automatisch auf die Erneuerung der ganzen Seite zurückgegriffen."
MOD_JEM_CAL_SHOW_CURRENT_EVENTS="Aktuelle Veranstaltungen anzeigen"
MOD_JEM_CAL_SHOW_CURRENT_EVENTS_DESC="Zeige aktuelle Veranstaltungen. Bitte nicht gleichzeitig dieses und archivierte Veranstaltungen wählen, da sonst nichts angezeigt werden kann!"
MOD_JEM_CAL_SHOW_ARCHIVED_EVENTS="Zeige archivierte Veranstaltungen"
MOD_JEM_CAL_SHOW_ARCHIVED_EVENTS_DESC="Zeige archivierte Veranstaltungen. Bitte nicht gleichzeitig dieses und aktuelle Veranstaltungen wählen, da sonst nichts angezeigt werden kann."
MOD_JEM_CAL_LIMIT_TO_CATEGORY_IDS="Beschränkung auf ausgewählte Kategorien"
MOD_JEM_CAL_LIMIT_TO_CATEGORY_IDS_DESC="Zeigt einen Kalender nur für die gewählte(n) Kategorie(n) an. Leer lassen für keine Einschränkung."
MOD_JEM_CAL_LIMIT_TO_VENUE_IDS="Beschränkung auf Lokalitäten"
MOD_JEM_CAL_LIMIT_TO_VENUE_IDS_DESC="Zeigt einen Kalender nur für die gewählte(n) Lokalität(en) an. Leerlassen gibt keine Einschränkung."
MOD_JEM_CAL_STRAIGHT_TO_DETAILS="Direkt zu den Details"
MOD_JEM_CAL_STRAIGHT_TO_DETAILS_DESC="Gehen Sie direkt zur Detailseite, wenn es nur eine Veranstaltung zur Auswahl gibt."
MOD_JEM_CAL_DEFAULT_CSS="Standard-CSS verwenden"
MOD_JEM_CAL_DEFAULT_CSS_DESC="Benutzt Standard Stylesheet  modules/mod_jem_cal/mod_jemcal.css"
MOD_JEM_CAL_USER_CSS="Alternative CSS verwenden"
MOD_JEM_CAL_USER_CSS_DESC="Verwende ein alternatives Stylesheet, z.B. modules/mod_jem_cal/mystylesheet.css. Bitte gib den vollständigen Pfad zu Ihrer CSS-Datei an, wie im Beispiel!"
MOD_JEM_CAL_MODULE_CLASS_SUFFIX="Modulklassen-Suffix"
MOD_JEM_CAL_MODULE_CLASS_SUFFIX_DESC="Ein Suffix, das an die CSS-Klasse des Moduls (table.moduletable) angehängt wird, ermöglicht ein individuelles Styling des Moduls."
MOD_JEM_CAL_DEFAULT_ITEM_ID="Standard-Menü-Item-ID"
MOD_JEM_CAL_DEFAULT_ITEM_ID_DESC="Überschreibe die Item-ID, die verwendet wird, wenn der Kalenderlink direkt zu Details zu einem Menüeintrag deiner Wahl führt."
MOD_JEM_CAL_EVENT="Veranstaltung"
MOD_JEM_CAL_EVENTS="Veranstaltungen"
MOD_JEM_CAL_CACHING="Caching"
MOD_JEM_CAL_CACHING_DESC="Lege fest, ob der Inhalt dieses Moduls zwischengespeichert werden soll."
MOD_JEM_CAL_CACHE_TIME="Cache Dauer"
MOD_JEM_CAL_CACHE_TIME_DESC="Die Zeit, bis das Modul erneut zwischengespeichert wird."
; Module intro and footer text
MOD_JEM_CAL_MODULE_TEXT_BLOCK="Intro- und Fußtext des Moduls"
MOD_JEM_CAL_SHOW_INTROTEXT="Kopftext anzeigen"
MOD_JEM_CAL_SHOW_INTROTEXT_DESC="Anzeige von benutzerdef. Text über Modulinhalt"
MOD_JEM_CAL_INTROTEXT="Kopftext"
MOD_JEM_CAL_INTROTEXT_DESC="Über Modulinhalt angezeigter Text"
MOD_JEM_CAL_SHOW_FOOTERTEXT="Fußzeile anzeigen"
MOD_JEM_CAL_SHOW_FOOTERTEXT_DESC="Anzeige von benutzerdef. Text nach Modulinhalt"
MOD_JEM_CAL_FOOTERTEXT="Fußtext"
MOD_JEM_CAL_FOOTERTEXT_DESC="Nach Modulinhalt angezeigter Text"

