; @package    JEM
; @subpackage JEM Upcoming Events Basic Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2005-2009 Christoph Lukes
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_EVENTS_IN_MODULE="Events im Modul"
MOD_JEM_EVENTS_IN_MODULE_DESC="Anzahl angezeigter Events im Modul."
MOD_JEM_UPCOMING_OR_ARCHIVED="Art angezeigter Events"
MOD_JEM_UPCOMING_OR_ARCHIVED_DESC="Wählen, ob kommende, laufende oder archivierte Events angezeigt werden sollen."
MOD_JEM_UPCOMING_EVENTS="Kommende Events"
MOD_JEM_UNFINISHED_EVENTS="Laufende Events"
MOD_JEM_ARCHIVED_EVENTS="Archivierte Events"
MOD_JEM_SHOW_NO_EVENTS="'Keine Events anzeigen, wenn keine solchen vorhanden"
MOD_JEM_SHOW_NO_EVENTS_DESC="Text anzeigen, wenn kein solcher Event gefunden wurde. Sonst wird das Modul nicht angezeigt."
MOD_JEM_HIGHLIGHT_FEATURED="Haupt-Event wird hervorgehoben"
MOD_JEM_HIGHLIGHT_FEATURED_DESC="Hebt Haupt-Events durch Fettschrift an."
MOD_JEM_OFFSET_HOURS="Zeitverschiebung (in Stunden)"
MOD_JEM_OFFSET_HOURS_DESC="Verschiebt Zeit in die Zukunft (positive Werte) oder in die Vergangenheit (negative Werte). Wird nur bei nicht archivierten Events verwendet. <br>Beispiele: Für die Anzeige wenigstens vor zwei Stunden beendeter Events, wähle unbeendete Events und Zeitverschiebung auf -2. Für die Anzeige von Events, die in einer Woche oder später beginnen, wähle kommende Events und Zeitverschiebung auf 168 (7*24)."
MOD_JEM_DISPLAY_ORDER="Anzeigereihenfolge"
MOD_JEM_DISPLAY_ORDER_DESC="Wähle die Reihenfolge für Titel, Datum und Veranstaltungsort."
MOD_JEM_ORDER_TDV="Titel, Datum, Veranstaltungsort"
MOD_JEM_ORDER_TVD="Titel, Veranstaltungsort, Datum"
MOD_JEM_ORDER_VTD="Veranstaltungsort, Titel, Datum"
MOD_JEM_ORDER_VDT="Veranstaltungsort, Datum, Titel"
MOD_JEM_ORDER_DTV="Datum, Titel, Veranstaltungsort"
MOD_JEM_ORDER_DVT="Datum, Veranstaltungsort, Titel"
MOD_JEM_TITLE_EVENT="Titel oder Veranstaltungsort anzeigen"
MOD_JEM_TITLE_EVENT_DESC="Wählen Sie, ob der Titel der Veranstaltung angezeigt werden soll."
MOD_JEM_VENUE="Name der Lokalität"
MOD_JEM_TITLE="Event-Titel"
MOD_JEM_MAX_TITLE_LENGTH="Max. Titel-Länge"
MOD_JEM_MAX_TITLE_LENGTH_DESC="Maximale Länge des Titels, die angezeigt wird."
MOD_JEM_LINK_TO_VENUE="Link zur Lokalität"
MOD_JEM_LINK_TO_VENUE_DESC="Verlinkt zur Lokalität, aber nur, wenn für Anzeige Lokalität gewählt wurde!"
MOD_JEM_SHOW_CATEGORY="Anzeige der Kategorie"
MOD_JEM_SHOW_CATEGORY_DESC="Soll die Event Kategorie angezeigt werden."
MOD_JEM_LINK_TO_CATEGORY="Link zur Kategorie"
MOD_JEM_LINK_TO_CATEGORY_DESC="Verlinkt die Eventkategorie, wenn sie angezeigt ist."
MOD_JEM_LINK_TO_EVENT="Link zum Event"
MOD_JEM_LINK_TO_EVENT_DESC="Link auf Datum oder Titel verlinkt zur Eventseite (wenn gewählt)."
MOD_JEM_EVENT_LINK_EVENT_LAYOUT="Layout des Event-Blocks"
MOD_JEM_EVENT_LINK_EVENT_LAYOUT_DESC="Erzwingen Sie optional das Layout der Event-Blöcke, wenn ein Event aus diesem Modul geöffnet wird."
MOD_JEM_EVENT_LINK_VENUE_LAYOUT="Layout des Lokalität s-Blocks"
MOD_JEM_EVENT_LINK_VENUE_LAYOUT_DESC="Erzwingen Sie optional das Layout der Lokalitäts-Blöcke, wenn Sie einen Event aus diesem Modul heraus öffnen."
MOD_JEM_EVENT_LINK_LAYOUT_DETAILS="Details"
MOD_JEM_EVENT_LINK_LAYOUT_COMPACT="Kompakt"
MOD_JEM_SHOW_MORE_INFORMATION="Mehr Infos"
MOD_JEM_SHOW_MORE_INFORMATION_DESC="Anzeige eines \"Mehr Info\" Links oder Taste, wenn der Event einen assoziierten Betrag hat."
MOD_JEM_SHOW_MORE_INFORMATION_TITLE="Mehr Infos anzeigen"
MOD_JEM_SHOW_MORE_INFORMATION_TITLE_DESC="Anzeige des Titels des assoziierten Textes nach dem 'Mehr Infos"
MOD_JEM_MORE_INFORMATION_LINK="Ja (Link)"
MOD_JEM_MORE_INFORMATION_BUTTON="Ja (Taste)"
MOD_JEM_SHOW_ICON_COUNTRY_VENUE="Länderflagge anzeigen"
MOD_JEM_SHOW_ICON_COUNTRY_VENUE_DESC="Eine kleine Länderflagge der Lokalität für jeden Event anzeigen."
MOD_JEM_SHOW_FLAG_ICON="Länder Icon"
MOD_JEM_DATE="Datum"
MOD_JEM_CATEGORY_ID="Kategorien"
MOD_JEM_CATEGORY_ID_DESC="Wähle Kategorien, deren Events angezeigt werden sollen. Leerlassen, wenn alle angezeigt werden sollen."
MOD_JEM_VENUE_ID="Lokalitäten"
MOD_JEM_VENUE_ID_DESC="Wähle Lokalitäten, deren Events angezeigt werden sollen. Leerlassen, wenn alle Events angezeigt werden sollen."
MOD_JEM_DATE_FORMAT="Datums-Format"
MOD_JEM_DATE_FORMAT_DESC="Datumsformat mit dem PHP-Datumsformat, z.B. 'Y-m-d' für 2017-06-15. Für weitere Infos bitte <a href='https://www.php.net/manual/de/datetime.format.php' target='_blank'>das PHP-Handbuch benutzen</a>."
MOD_JEM_TIME_FORMAT="Zeit-Format"
MOD_JEM_TIME_FORMAT_DESC="Zeit-Format verwendet das PHP Zeit-Format, z.B. 'H:i'. Für weitere Infos bitte <a href='https://www.php.net/manual/de/datetime.format.php' target='_blank'>das PHP-Handbuch benutzen</a>"
MOD_JEM_MODULE_CLASS_SUFFIX="Modul Class Suffix"
MOD_JEM_MODULE_CLASS_SUFFIX_DESC="Ein Suffix für die CSS Klasse des Moduls. Dies erlaubt individuelleres Styling."
MOD_JEM_CACHING="Caching"
MOD_JEM_CACHING_DESC="Wählen ob Inhalt dieses Moduls gecachet werden soll."
MOD_JEM_NO_CACHING="Kein Caching"
MOD_JEM_CACHE_TIME="Cache-Zeitdauer"
MOD_JEM_CACHE_TIME_DESC="Die Zeit, bis das Modul erneut zwischengespeichert wird."
MOD_JEM="JEM Basis-Modul"
MOD_JEM_XML_DESCRIPTION="JEM Basis-Modul <br>Zeigt Events in einer Modul-Position an."
MOD_JEM_EVENT_TREE_MODE="Ereignis-Hierarchie"
MOD_JEM_EVENT_TREE_MODE_DESC="Wählen Sie, ob dieses Modul Top-Events, Programmartikel oder beides anzeigt."
MOD_JEM_EVENT_TREE_MODE_CALENDAR="Kalenderstandard"
MOD_JEM_EVENT_TREE_MODE_PARENTS="Nur übergeordnete Ereignisse"
MOD_JEM_EVENT_TREE_MODE_CHILDREN="Nur Subevents"
MOD_JEM_EVENT_TREE_MODE_ALL="Übergeordnete Ereignisse und Subevents"

; Frontend
MOD_JEM_NO_EVENTS="Kein solcher Event gefunden"
MOD_JEM_MORE_INFORMATION="Mehr Infos"
MOD_JEM_ALL_DAY="Ganztägig"
; Module intro and footer text
MOD_JEM_MODULE_TEXT_BLOCK="Kopf- und Fußtext des Moduls"
MOD_JEM_SHOW_INTROTEXT="Kopftext anzeigen"
MOD_JEM_SHOW_INTROTEXT_DESC="Anzeige von benutzerdef. Text über Modulinhalt"
MOD_JEM_INTROTEXT="Kopftext"
MOD_JEM_INTROTEXT_DESC="Über Modulinhalt angezeigter Text"
MOD_JEM_SHOW_FOOTERTEXT="Fußzeile anzeigen"
MOD_JEM_SHOW_FOOTERTEXT_DESC="Anzeige von benutzerdef. Text nach Modulinhalt"
MOD_JEM_FOOTERTEXT="Fußtext"
MOD_JEM_FOOTERTEXT_DESC="Nach Modulinhalt angezeigter Text"

