; @package    JEM
; @subpackage JEM Map Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_MAP="JEM - Lokalitäten Karten Modul"
MOD_JEM_MAP_XML_DESCRIPTION="Dieses Modul zeigt eine Karte aller Lokalitäten mit eingegebener Adresse, Länge und Breite"
MOD_JEM_MAP_EVENT_TREE_MODE="Ereignis-Hierarchie"
MOD_JEM_MAP_EVENT_TREE_MODE_DESC="Wählen Sie, ob dieses Modul Top-Events, Programmartikel oder beides anzeigt."
MOD_JEM_MAP_EVENT_TREE_MODE_CALENDAR="Kalenderstandard"
MOD_JEM_MAP_EVENT_TREE_MODE_PARENTS="Nur übergeordnete Ereignisse"
MOD_JEM_MAP_EVENT_TREE_MODE_CHILDREN="Nur Subevents"
MOD_JEM_MAP_EVENT_TREE_MODE_ALL="Übergeordnete Ereignisse und Subevents"
MOD_JEM_MAP_VENUE_MARKER="Pfad zum Marker Bild für Örtlichkeiten"
MOD_JEM_MAP_VENUE_MARKER_DESC="Gib den Pfad zum benutzerdefinierten Marker Icon (SVG/PNG) für Örtlichkeiten an."
MOD_JEM_MAP_MYLOC_MARKER="Marker Bild für 'Du bist hier'"
MOD_JEM_MAP_MYLOC_MARKER_DESC="Gib den Pfad zum benutzerdefinierten Marker Icon (SVG/PNG) für 'Du bist hier' an."
MOD_JEM_MAP_HEIGHT="Kartenhöhe"
MOD_JEM_MAP_HEIGHT_DESC="Höhe des Karten-Containers (z.B. 400px, 60vh)"
MOD_JEM_MAP_ZOOM="Standart Kartenzoom"
MOD_JEM_MAP_ZOOM_DESC="Zoom-Ebene: 0 (ganze Welt) bis 19 (Straßen-Detail)"
MOD_JEM_MAP_PROVIDER="Karten-Provider"
MOD_JEM_MAP_PROVIDER_DESC="Wähle den verwendeten Karten-Provider für diese Karte. OpenStreetMap verwendet die aktuelle Leaflet-Karte. Google Maps benötigt den in den JEM Einstellungen angegebenen Google API Schlüssel."
MOD_JEM_MAP_PROVIDER_OSM="OpenStreetMap / Blatt"
MOD_JEM_MAP_PROVIDER_GOOGLE="Google Maps"
MOD_JEM_MAP_SHOW_DIRECTIONS_LINK="Anzeige von Navigations-Links"
MOD_JEM_MAP_SHOW_DIRECTIONS_LINK_DESC="Anzeige eines Links zur Routenmarkierung an."
MOD_JEM_MAP_SHOW_FULL_MAP_LINK="Anzeige eines Links für Vollansicht der Karte."
MOD_JEM_MAP_SHOW_FULL_MAP_LINK_DESC="Anzeige eines Links in den Pop-ups der Kartenmarkierungen zur vollständigen Kartenansicht an."
MOD_JEM_MAP_SHOW_DATE_FILTER="Datums-Filter anzeigen"
MOD_JEM_MAP_SHOW_DATE_FILTER_DESC="Zeigt einen Datums-Filter über der Karte an, der Lokalitäten mit Events an bestimmten Datum anzeigt."
MOD_JEM_MAP_SHOW_CATEGORY_FILTER="Kategoriefilter anzeigen"
MOD_JEM_MAP_SHOW_CATEGORY_FILTER_DESC="Zeige oberhalb der Karte eine Kategorieauswahl an. Wenn Kategorien unten konfiguriert sind, stehen nur diese Kategorien zur Verfügung."
MOD_JEM_MAP_CATEGORY_FILTER="Kategoriefilter"
MOD_JEM_MAP_ALL_CATEGORIES="Alle Kategorien"
MOD_JEM_MAP_SHOW_COUNTRY_FILTER="Bundeslandfilter anzeigen"
MOD_JEM_MAP_SHOW_COUNTRY_FILTER_DESC="Zeigt eine Wahlmöglichkeit für Regionen über der Karte an."
MOD_JEM_MAP_COUNTRY_FILTER="Länderfilter"
MOD_JEM_MAP_ALL_COUNTRIES="Alle Länder"
MOD_JEM_MAP_DEFAULT_COUNTRY="Standard-Region"
MOD_JEM_MAP_DEFAULT_COUNTRY_DESC="Wähle das verwendete Land als Standard für die Karte. Leerlassen, um Lokalitäten aller Länder anzuzeigen.\n\n\n"
MOD_JEM_MAP_DATE_FILTER_DEFAULT="Standard Datumsfilter"
MOD_JEM_MAP_DATE_FILTER_DEFAULT_DESC="Wähle den Datumsfilter aus, der standardmäßig beim Laden des Moduls angewendet wird."
MOD_JEM_MAP_YOU_ARE_HERE="Du  bist hier!"
MOD_JEM_MAP_APPLY="Anwenden"
MOD_JEM_MAP_ALL="Alle "
MOD_JEM_MAP_DATE="Datum"
MOD_JEM_MAP_TODAY="Heute"
MOD_JEM_MAP_TOMORROW="Morgen"
MOD_JEM_MAP_WEEK="Diese Woche"
MOD_JEM_MAP_MONTH="Diesen Monat"
MOD_JEM_MAP_YEAR="Dieses Jahr"
MOD_JEM_MAP_NAVIGATE="Anreise"
MOD_JEM_MAP_OPEN_FULL_MAP="Öffne Karte als Vollbild"
MOD_JEM_MAP_AUTO_CENTER="Automatische Zentrierung der Karte"
MOD_JEM_MAP_AUTO_CENTER_DESC="Zentriert Karte automatisch auf die angezeigten Event-Lokalitäten"
MOD_JEM_MAP_CENTER_LATITUDE="Geogr. Breite der Kartenmitte"
MOD_JEM_MAP_CENTER_LATITUDE_DESC="Breitenkoordinate für Kartenmitte (Standart: Mitteleuropa)"
MOD_JEM_MAP_CENTER_LONGITUDE="Geogr. Länge der Kartenmitte"
MOD_JEM_MAP_CENTER_LONGITUDE_DESC="Längenkoordinate für Kartenmitte (Standart: Mitteleuropa)"
MOD_JEM_MAP_SHOW_MY_LOCATION="Wo bin ich?"
MOD_JEM_MAP_SHOW_MY_LOCATION_DESC="Anzeige des aktuellen Standorts. Benötigt Browser-Bewilligung für Lokalisierung."
MOD_JEM_MAP_FULLSCREEN_TITLE="Anzeige der Karte im Vollbild"
MOD_JEM_MAP_CATEGORY_ID="Kategorien"
MOD_JEM_MAP_CATEGORY_ID_DESC="Kategorien wählen, wenn nur deren Events angezeigt werden sollen. Leerlassen, wenn alle Events angezeigt werden sollen."
MOD_JEM_MAP_FULLSCREEN_EXIT="Vollbild verlassen"
MOD_JEM_MAP_GEOLOCATION_NOT_SUPPORTED="Lokalisierung ist von deinem Browser nicht zugelassen."
MOD_JEM_MAP_LOCATION_ERROR="Kann Standort nicht lokalisieren. Bitte prüfe deine Browser-Bewilligung und versuche nochmals."
MOD_JEM_MAP_LOCATION_HELP="Klicken Sie auf 'Meinen Standort anzeigen', um Ihre aktuelle Position auf der Karte zu finden."
MOD_JEM_MAP_PERMISSION_INSTRUCTIONS="Dein Browser fragt nach Bewilligung. Bitte 'erlauben' anklicken um fortzufahren."
MOD_JEM_MAP_LOCATING="Benötigt Lokalisierung"
MOD_JEM_MAP_PERMISSION_DENIED="Lokalisierung verweigert. Bitte erlaube Lokalisierung in deinen Browser-Einrichtung und versuche nochmals"
MOD_JEM_MAP_POSITION_UNAVAILABLE="Lokalisierung ist nicht möglich. Bitte prüfe deine Settings und versuche nochmals."
MOD_JEM_MAP_TIMEOUT="Lokalisierungszeit ist abgelaufen. Versuch es nochmals!"
MOD_JEM_MAP_HEAT_LAYER="Dichtemarkierung einrichten"
MOD_JEM_MAP_HEAT_LAYER_DESC="Dichtemarkierung aktivieren, um Event-Häufungen anzuzeigen."
MOD_JEM_MAP_FULL_SCREEN="Vollbild-Schalter"
MOD_JEM_MAP_FULL_SCREEN_DESC="Aktiviere diese Oprtion, um einen Schalter anzuzeigen, der die Karte als Vollbild anzeigt."
MOD_JEM_MODULE_CLASS_SUFFIX="Modulklassen-Suffix"
MOD_JEM_MODULE_CLASS_SUFFIX_DESC="Ein Suffix, das an die CSS-Klasse des Moduls angehängt wird und die individuelle Gestaltung des Moduls ermöglicht."
MOD_JEM_CACHING="Caching"
MOD_JEM_CACHING_DESC="Wähle, ob der Inhalt des Moduls gecached werden soll."
MOD_JEM_NO_CACHING="Kein Caching"
MOD_JEM_CACHE_TIME="Cache Dauer"
MOD_JEM_CACHE_TIME_DESC="Die Zeit, bis das Modul erneut zwischengespeichert wird."
; Module intro and footer text
MOD_JEM_MAP_MODULE_TEXT_BLOCK="Intro- und Fußtext des Moduls"
MOD_JEM_MAP_SHOW_INTROTEXT="Kopftext anzeigen"
MOD_JEM_MAP_SHOW_INTROTEXT_DESC="Anzeige von benutzerdef. Text über Modulinhalt"
MOD_JEM_MAP_INTROTEXT="Kopftext"
MOD_JEM_MAP_INTROTEXT_DESC="Über Modulinhalt angezeigter Text"
MOD_JEM_MAP_SHOW_FOOTERTEXT="Fußzeile anzeigen"
MOD_JEM_MAP_SHOW_FOOTERTEXT_DESC="Anzeige von benutzerdef. Text nach Modulinhalt"
MOD_JEM_MAP_FOOTERTEXT="Fußtext"
MOD_JEM_MAP_FOOTERTEXT_DESC="Nach Modulinhalt angezeigter Text"

