; @package    JEM
; @subpackage JEM Teaser Module
; @copyright  (C) 2013-2026 joomlaeventmanager.net
; @copyright  (C) 2005-2009 Christoph Lukes
; @license    https://www.gnu.org/licenses/gpl-3.0 GNU/GPL
;
; All translations can be found at https://app.transifex.com/jemproject/
; Please join the translation team if you want to contribute your changes to the translations
;
; Note: All ini files need to be saved as UTF-8, no BOM

MOD_JEM_TEASER_EVENTS_IN_MODULE="Anzahl Events"
MOD_JEM_TEASER_EVENTS_IN_MODULE_DESC="Anzahl angezeigter Events im Modul"
MOD_JEM_TEASER_UPCOMING_ARCHIVED_OR_CURRENT="Art der Eventsanzeige"
MOD_JEM_TEASER_UPCOMING_ARCHIVED_OR_CURRENT_DESC="Wählen, ob kommende, laufende oder archivierte Events angezeigt werden sollen."
MOD_JEM_TEASER_UPCOMING_EVENTS="Kommende"
MOD_JEM_TEASER_UNFINISHED_EVENTS="Laufende"
MOD_JEM_TEASER_ARCHIVED_EVENTS="Archivierte"
MOD_JEM_TEASER_CURRENT_EVENTS="Heutige"
MOD_JEM_TEASER_FEATURED_EVENTS="Hervorgehobene"
MOD_JEM_TEASER_SHOW_NO_EVENTS="'Keine Events' anzeigen, wenn keine solchen vorhanden"
MOD_JEM_TEASER_SHOW_NO_EVENTS_DESC="Text anzeigen, wenn kein solcher Event gefunden wurde. Sonst wird das Modul nicht angezeigt."
MOD_JEM_TEASER_OFFSET_HOURS="Zeitverschiebung (in Stunden)"
MOD_JEM_TEASER_OFFSET_HOURS_DESC="Verschiebt die Zeit in die Zukunft (mit positiven Werten) oder in die Vergangenheit (mit negativen Werten). Wird nur für nicht archivierte Events verwendet. Bei heutigen Veranstaltungen wird gerundet auf ganze Tage.<br>Beispiele: Zur Anzeige von Veranstaltungen, die wenigstens vor zwei Stunden beendet wurden, Typ auf 'unbeendet' und Zeitverschiebung auf '-2' setzen. Für Veranstaltungen, die erst in einer Woche oder später beginnen, Typ auf kommend und Offset auf 168 (7 * 24) setzen. Zur Anzeige von morgigen Veranstaltungen, Typ auf 'Heute' und Zeitverschiebung auf '24' setzen."
MOD_JEM_TEASER_VENUE="Lokalität"
MOD_JEM_TEASER_MAX_TITLE_LENGTH="Max. Titellänge"
MOD_JEM_TEASER_MAX_TITLE_LENGTH_DESC="Maximale Länge des Titels"
MOD_JEM_TEASER_LINK_TO_DETAILS="Link zur Veranstaltung auf Titel"
MOD_JEM_TEASER_LINK_TO_DETAILS_DESC="Link zur Veranstaltungsseite auf Titel"
MOD_JEM_TEASER_EVENT_LINK_EVENT_LAYOUT="Layout des Event-Blocks"
MOD_JEM_TEASER_EVENT_LINK_EVENT_LAYOUT_DESC="Erzwingen Sie optional das Layout der Ereignisblöcke, wenn ein Ereignis aus diesem Modul geöffnet wird."
MOD_JEM_TEASER_EVENT_LINK_VENUE_LAYOUT="Layout des Lokalitäts-Blocks"
MOD_JEM_TEASER_EVENT_LINK_VENUE_LAYOUT_DESC="Erzwingen Sie optional das Layout der Lokalitäts-Blöcke, wenn Sie einen Event aus diesem Modul heraus öffnen."
MOD_JEM_TEASER_EVENT_LINK_LAYOUT_DETAILS="Details"
MOD_JEM_TEASER_EVENT_LINK_LAYOUT_COMPACT="Kompakt"
MOD_JEM_TEASER_LINK_TO_CATEGORY="Link zur Kategorie"
MOD_JEM_TEASER_LINK_TO_CATEGORY_DESC="Link zur Kategorie"
MOD_JEM_TEASER_SHOW_CATEGORY="Kategorie anzeigen"
MOD_JEM_TEASER_SHOW_CATEGORY_DESC="Soll die Event Kategorie angezeigt werden"
MOD_JEM_TEASER_SHOW_VENUE="Lokalität anzeigen"
MOD_JEM_TEASER_SHOW_VENUE_DESC="Soll die Eventlokalität angezeigt werden?"
MOD_JEM_TEASER_LINK_TO_VENUE="Link zur Lokalität"
MOD_JEM_TEASER_LINK_TO_VENUE_DESC="Link zur Lokalität"
MOD_JEM_TEASER_SHOW_DESCRIPTION_EVENT="Eventbeschreibung anzeigen"
MOD_JEM_TEASER_SHOW_DESCRIPTION_EVENT_DESC="Eventbeschreibung anzeigen"
MOD_JEM_TEASER_SHOW_IMAGE_EVENT="Eventbild anzeigen"
MOD_JEM_TEASER_SHOW_IMAGE_EVENT_DESC="Zeigt Eventbild an."
MOD_JEM_TEASER_SHOW_IMAGE_VENUE="Lokalitätsbild anzeigen"
MOD_JEM_TEASER_SHOW_IMAGE_VENUE_DESC="Zeigt Bild der Lokalität an."
MOD_JEM_TEASER_USE_MODAL="Modales Fenster"
MOD_JEM_TEASER_USE_MODAL_DESC="Das Modal-Fesnter zeigt nach einem Klick das Bild in Originalgröße mit einem hübschen Effekt im aktiven Bildschirm"
MOD_JEM_TEASER_DATE="Datum"
MOD_JEM_TEASER_CATEGORY_ID="Kategorien"
MOD_JEM_TEASER_CATEGORY_ID_DESC="Kategorien wählen, deren Events nur angezeigt werden sollen. Leerlassen, wenn alle Events angezeigt werden sollen."
MOD_JEM_TEASER_VENUE_ID="Lokalitäten"
MOD_JEM_TEASER_VENUE_ID_DESC="Lokalitäten auswählen, deren Events nur angezeigt werden sollen. Leerlassen, um alle Events anzuzeigen."
MOD_JEM_TEASER_EVENT_ID="Event-ID"
MOD_JEM_TEASER_EVENT_ID_DESC="Mit Komma getrennte Event-IDs eingeben, um auf die gewählten zu begrenzen. Leerlassen für alle."
MOD_JEM_TEASER_STATE="Bundesland"
MOD_JEM_TEASER_STATE_DESC="Mit Komma getrennte Regionen/Bundesländer eingeben, um auf die gewählten zu begrenzen. Leerlassen für alle."
MOD_JEM_TEASER_STATE_MODE="Bundesland Übereinstimmungs Modus"
MOD_JEM_TEASER_STATE_MODE_DESC="Wählen, ob beim Bundesland die oben eingegebenen Zeichen vollständig übereinstimmen sollen oder nur enthalten sein sollen."
MOD_JEM_TEASER_STATE_MODE_EXACTMATCH="Vollständige Übereinstimmung"
MOD_JEM_TEASER_STATE_MODE_CONTAINS="Enthält"
MOD_JEM_TEASER_COUNTRIES="Länder"
MOD_JEM_TEASER_COUNTRIES_DESC="Länder wählen, deren Events nur angezeigt werden sollen. Leer lassen, wenn alle Events angezeigt werden sollen."
MOD_JEM_TEASER_SHOW_DATE="Datum anzeigen"
MOD_JEM_TEASER_SHOW_DAY_DIFFERENCE="Differenz von Tagen anzeigen"
MOD_JEM_TEASER_SHOW_DATE_OR_DAY_DIFFERENCE="Datum Anzeigeart"
MOD_JEM_TEASER_SHOW_DATE_OR_DAY_DIFFERENCE_DESC="Auswählen, um das formatierte Datum oder den Unterschied zwischen dem aktuellen Tag und dem Event-Datum anzuzeigen. Hinweis: Die Zeit wird ausgeblendet, wenn der Tagunterschied ausgewählt wird."
MOD_JEM_TEASER_DATE_FORMAT="Datumsformat"
MOD_JEM_TEASER_DATE_FORMAT_DESC="Datumsformat mit dem PHP-Datumsformat, z.B. 'Y-m-d' für 2017-06-15. Für weitere Infos bitte <a href='https://www.php.net/manual/en/datetime.format.php' target='_blank'>das PHP-Handbuch benutzen</a>."
MOD_JEM_TEASER_TIME_FORMAT="Zeitformat"
MOD_JEM_TEASER_TIME_FORMAT_DESC="Zeit-Format verwendet das PHP Zeit-Format, z.B. 'H:i'. Für weitere Infos bitte <a href='https://www.php.net/manual/en/datetime.format.php' target='_blank'>das PHP-Handbuch benutzen</a>."
MOD_JEM_TEASER_MODULE_CLASS_SUFFIX="Modulklassen-Suffix"
MOD_JEM_TEASER_MODULE_CLASS_SUFFIX_DESC="Ein Suffix für die CSS-Klasse des Moduls. Dies erlaubt ein individuelles Styling des Moduls."
MOD_JEM_TEASER_CACHING="Caching"
MOD_JEM_TEASER_CACHING_DESC="Wie soll das Modul zwischengespeichert werden"
MOD_JEM_TEASER_CACHE_TIME="Cache-Zeitdauer"
MOD_JEM_TEASER_CACHE_TIME_DESC="Die Zeit, bis das Modul erneut zwischengespeichert wird."
MOD_JEM_TEASER_ALLOW_LINEBREAK="Zeilenumbruch erlauben"
MOD_JEM_TEASER_ALLOW_LINEBREAK_DESC="Erlaubt Zeilenumbruch oder Ersatz durch Leerschlag"
MOD_JEM_TEASER_COLOR="Farbe des Kalenderblatts"
MOD_JEM_TEASER_COLOR_DESC="Farbe des Kalenderblatts. 'von der Kategorie': die Kategoriefarbe wird verwendet, sofern die Farbe einzig ist, sonst Ersatz-Farbe. 'von der Lokalität': die Farbe der Lokalität wird verwendet, sofern vorhanden, sonst die Ersatzfarbe."
MOD_JEM_TEASER_MAX_DESCRIPTION_LENGTH="maximale Länge der Beschreibung"
MOD_JEM_TEASER_MAX_DESCRIPTION_LENGTH_DESC="Begrenzung der Beschreibung auf diese Anzahl Zeichen."
MOD_JEM_TEASER_BLUE="Blau"
MOD_JEM_TEASER_GREEN="Grün"
MOD_JEM_TEASER_ORANGE="Orange"
MOD_JEM_TEASER_RED="Rot"
MOD_JEM_TEASER_CATEGORY_COLOR="von der Kategorie-Farbe"
MOD_JEM_TEASER_VENUE_COLOR="von der Lokalitäts-Farbe"
MOD_JEM_TEASER_FALLBACK_COLOR="Ersatzfarbe"
MOD_JEM_TEASER_FALLBACK_COLOR_DESC="Verwendete Farbe in HEX Code, wenn oben 'Ersatzfarbe' oder 'Kategorie-Farbe' gewählt wurde."
MOD_JEM_TEASER_FIELD_READMORE_DESC="Wenn „Ja“, dann wird der Link „Weiterlesen …“ angezeigt, wenn die Beschreibung der Veranstaltung einen „Weiterlesen“-Absatz enthält"
MOD_JEM_TEASER_FIELD_READMORE_LABEL="'Weiterlesen …' anzeigen"
MOD_JEM_TEASER_SHOW_MORE_INFORMATION="Mehr Infos"
MOD_JEM_TEASER_SHOW_MORE_INFORMATION_DESC="Anzeige eines \"Mehr Info\" Links oder Taste, wenn der Event einen assoziierten Betrag hat."
MOD_JEM_TEASER_SHOW_MORE_INFORMATION_TITLE="Mehr Infos anzeigen"
MOD_JEM_TEASER_SHOW_MORE_INFORMATION_TITLE_DESC="Anzeige des Titels des assoziierten Textes nach dem 'Mehr Infos' Link.\n"
MOD_JEM_TEASER_READMORE_LINK="Ja (Link)"
MOD_JEM_TEASER_READMORE_BUTTON="Ja (Taste)"
MOD_JEM_TEASER_MORE_INFORMATION_LINK="Ja (Link)"
MOD_JEM_TEASER_MORE_INFORMATION_BUTTON="Ja (Taste)"

MOD_JEM_TEASER="JEM - Teaser-Module"
MOD_JEM_TEASER_XML_DESCRIPTION="JEM Latest Events Teaser Modul"

; Frontend
MOD_JEM_TEASER_TODAY="Heute"
MOD_JEM_TEASER_TOMORROW="Morgen"
MOD_JEM_TEASER_YESTERDAY="Gestern"
MOD_JEM_TEASER_DAYS_AGO="vor %s Tag"
MOD_JEM_TEASER_DAYS_AHEAD="in %s Tagen"
MOD_JEM_TEASER_ENDED_DAYS_AGO="Endete vor %s Tagen"
MOD_JEM_TEASER_STARTED_DAYS_AGO="Begann vor %s Tagen"
MOD_JEM_TEASER_FROM="%s"
MOD_JEM_TEASER_UNTIL="- %s"
MOD_JEM_TEASER_FROM_UNTIL="%s - %s"
MOD_JEM_TEASER_ON_DATE="%s"
MOD_JEM_TEASER_READMORE="Weiterlesen …"
MOD_JEM_TEASER_MORE_INFORMATION="Mehr Infos"
MOD_JEM_TEASER_READMORE_REGISTER="?Weiterlesen aktivieren?"
; MOD_JEM_TEASER_NO_DESCRIPTION=""
MOD_JEM_TEASER_NO_EVENTS="Kein solcher Event gefunden"
MOD_JEM_TEASER_ALL_DAY="Ganztägig"
MOD_JEM_TEASER_VENUE_COLOR_LABEL="Verwende Lokalitätsfarbe"
MOD_JEM_TEASER_VENUE_COLOR_DESC="Verwendet Lokalitätsfarbe bei der Anzeige des Eventlokals"
MOD_JEM_TEASER_CATEGORY_COLOR_LABEL="Kategoriefarbe verwenden"
MOD_JEM_TEASER_CATEGORY_COLOR_DESC="Verwende Kategorie-Farbe im Kategorie-Label"
MOD_JEM_TEASER_COLOR_NO="Nein"
MOD_JEM_TEASER_COLOR_TEXT="Ja, als Textfarbe"
MOD_JEM_TEASER_COLOR_BG="Ja, als Texthintergrund"
; Module intro and footer text
MOD_JEM_TEASER_MODULE_TEXT_BLOCK="Intro- und Fußtext des Moduls"
MOD_JEM_TEASER_SHOW_INTROTEXT="Kopftext anzeigen"
MOD_JEM_TEASER_SHOW_INTROTEXT_DESC="Anzeige von benutzerdef. Text über Modulinhalt"
MOD_JEM_TEASER_INTROTEXT="Kopftext"
MOD_JEM_TEASER_INTROTEXT_DESC="Über Modulinhalt angezeigter Text"
MOD_JEM_TEASER_SHOW_FOOTERTEXT="Fußzeile anzeigen"
MOD_JEM_TEASER_SHOW_FOOTERTEXT_DESC="Anzeige von benutzerdef. Text nach Modulinhalt"
MOD_JEM_TEASER_FOOTERTEXT="Fußtext"
MOD_JEM_TEASER_FOOTERTEXT_DESC="Nach Modulinhalt angezeigter Text"

